### ISSUE TITLE
调试不方便，如果调试出错，就必须重启微信才可以

### ISSUE THREAD

**Issue by jowenz** [ljc545w/ComWeChatRobot#10]
用CWeChatRobot调试不太方便，代码没写好，就出错了，只能重启微信，WeChatTools.exe 好像用不了。

**Comment by ljc545w** [comment]
后续考虑加个Diaglog作为调试用，不过不会那么快。

**Comment by ljc545w** [comment]
> 用CWeChatRobot调试不太方便，代码没写好，就出错了，只能重启微信，WeChatTools.exe 好像用不了。

添加Dialog的计划可能要难产了，因为我发现可以在VS中配置调试。
调试DLL的话，需要在DWeChatRobot->属性->调试中将命令设置为WeChat.exe的绝对路径，通过VS调试器启动微信（因互斥体的存在启动调试前需退出别的微信进程），再使用`WeChatTools.exe DWeChatRobot.dll`注入（卸载命令为`WeChatTools.exe -r DWeChatRobot.dll`），如果dllmain中有添加断点就可以正常命中。
如果需要调试COM，则要在CWeChatRobot->属性->调试中添加命令参数：`/regserver`，启动调试器，外部调用COM的时候可以触发断点。
注意，调试时平台配置必须是Debug。

**Comment by whatarey** [comment]
大哥，有个问题就是 获取好友的微信id，就是您写的 C#demo 这里， 我用vs 重启运行几次，个人信息就会获取不到，然后打印好友微信id 就会报错，但是上面的实例都拿到了

**Comment by ljc545w** [comment]
> 大哥，有个问题就是 获取好友的微信id，就是您写的 C#demo 这里， 我用vs 重启运行几次，个人信息就会获取不到，然后打印好友微信id 就会报错，但是上面的实例都拿到了

暂时没有复现这个问题，不过发现Debug版本个人信息不能正确传回COM，那也就没办法返回到调用。Release版本试了几遍都是好的，后面我试着先把那个问题解决下。

**Comment by whatarey** [comment]
我是用你 Release 的 exe注册COM的， 下班了我录个视频给大哥你看看(ps:这东西不影响)

**Comment by shangdev** [comment]
请问 `通过VS调试器启动微信` 这个怎么操作？@ljc545w

**Comment by ljc545w** [comment]
> 请问 `通过VS调试器启动微信` 这个怎么操作？@ljc545w

在DWeChatRobot->属性->调试中将命令设置为WeChat.exe的绝对路径，平台配置选Debug，弄好后直接启动调试器

**Comment by jowenz** [comment]
> > 用CWeChatRobot调试不太方便，代码没写好，就出错了，只能重启微信，WeChatTools.exe 好像用不了。
> 
> 添加Dialog的计划可能要难产了，因为我发现可以在VS中配置调试。 调试DLL的话，需要在DWeChatRobot->属性->调试中将命令设置为WeChat.exe的绝对路径，通过VS调试器启动微信（因互斥体的存在启动调试前需退出别的微信进程），再使用`WeChatTools.exe DWeChatRobot.dll`注入（卸载命令为`WeChatTools.exe -r DWeChatRobot.dll`），如果dllmain中有添加断点就可以正常命中。 如果需要调试COM，则要在CWeChatRobot->属性->调试中添加命令参数：`/regserver`，启动调试器，外部调用COM的时候可以触发断点。 注意，调试时平台配置必须是Debug。

不好意思，是我没说清楚（不是用VS调试），我说的是用你 Release 的 exe注册COM的， 然后用python调用，如果没有写python没有写好，异常中断的话，或者调用参数错误的话，出断中断的话，大部分是必须退出微信后重新登录才可以。之前也有其他一些类似的hook。好像试过的两个都不会因为调用中断就必须要后启微信。

**Comment by ljc545w** [comment]
> > > 用CWeChatRobot调试不太方便，代码没写好，就出错了，只能重启微信，WeChatTools.exe 好像用不了。
> > 
> > 
> > 添加Dialog的计划可能要难产了，因为我发现可以在VS中配置调试。 调试DLL的话，需要在DWeChatRobot->属性->调试中将命令设置为WeChat.exe的绝对路径，通过VS调试器启动微信（因互斥体的存在启动调试前需退出别的微信进程），再使用`WeChatTools.exe DWeChatRobot.dll`注入（卸载命令为`WeChatTools.exe -r DWeChatRobot.dll`），如果dllmain中有添加断点就可以正常命中。 如果需要调试COM，则要在CWeChatRobot->属性->调试中添加命令参数：`/regserver`，启动调试器，外部调用COM的时候可以触发断点。 注意，调试时平台配置必须是Debug。
> 
> 不好意思，是我没说清楚（不是用VS调试），我说的是用你 Release 的 exe注册COM的， 然后用python调用，如果没有写python没有写好，异常中断的话，或者调用参数错误的话，出断中断的话，大部分是必须退出微信后重新登录才可以。之前也有其他一些类似的hook。好像试过的两个都不会因为调用中断就必须要后启微信。

关于异常，python和C++确实都没有捕捉，如果是参数类型错误应该不至于崩溃，COM组件会先报错，暂时不清楚此时还能不能调用StopService卸载DLL。后面我会做一些测试。暂时的建议是，StartService和StopService两个接口配套调用，其他的调用代码写在python的try-except块中，这样遇到错误也可以正常卸载DLL。

**Comment by Marber-seven** [comment]
可以加个QQ联系吗？

**Comment by koftcl** [comment]
ThreadRobot.robot.CReceiveMessage() 报错 invalid index

**Comment by ljc545w** [comment]
> 可以加个QQ联系吗？

您可以留下您的联系方式，我看到会加。

**Comment by ljc545w** [comment]
> 

这个错误，可能是使用的comtypes的版本较低，消息为空时数组越界了。

**Comment by koftcl** [comment]
> > 
> 
> 这个错误，可能是使用的comtypes的版本较低，消息为空时数组越界了。

谢谢，已启动，获取个人信息以及发送消息成功了，接收消息失败，使用的是master分支下 Release 文件夹下的 CWeChatRobot.exe 微信版本 3.6.0.18

**Comment by whatarey** [comment]
为啥我总是收到这个邮箱

![image](https://user-images.githubusercontent.com/35121432/170854078-f835e268-fce5-40ef-960c-aedd05b966c2.png)
