### ISSUE TITLE
之前看过这个项目，但感觉对使用者调用还是复杂了，最近研究了，也开源了一个更简易的python接口

### ISSUE THREAD

**Issue by smallevilbeast** [ljc545w/ComWeChatRobot#100]
项目地址： https://github.com/smallevilbeast/ntchat

可以一起交流下

**Comment by ljc545w** [comment]
好的。对不了解com的确实是有点复杂，最开始选择的道路比较偏。
不过现在已经提供了http调用，好了一点点。

**Comment by lihato** [comment]
原来咱们的ntchat是从这里得到的启发。期盼共同进步。
