### ISSUE TITLE
python demo 运行大概1小时,微信崩溃了

### ISSUE THREAD

**Issue by September999999999** [ljc545w/ComWeChatRobot#101]
![Snipaste_2022-08-30_11-11-59](https://user-images.githubusercontent.com/32701871/187340654-8e842eeb-a747-44fd-9d05-30440471be66.png)
[WeChat1a2cfd9d.txt](https://github.com/ljc545w/ComWeChatRobot/files/9449282/WeChat1a2cfd9d.txt)
[WeChat1a2cfd9dFMD5.txt](https://github.com/ljc545w/ComWeChatRobot/files/9449283/WeChat1a2cfd9dFMD5.txt)

**Comment by September999999999** [comment]
python 端没有输出报错

**Comment by ljc545w** [comment]
最好提供下崩溃时在进行的操作，这样不好判断是哪个接口导致的。还有，再崩溃的时候不要勾选发送错误报告。。这是在告诉tx你在使用插件。

**Comment by September999999999** [comment]
好的...,我明天再观察下

**Comment by cyonjan** [comment]
同样的问题反复出现，报告是SWechatRobot模块存取权限错误，刚开始一切ok，突然出现一次后，就肯定发生，就是在start_listen后，调用API接口（我试的selfinfo和contactlist)，但是调用APIS.WECHAT_MSG_START_HOOK倒没问题。

**Comment by ljc545w** [comment]
暂时无法复现到问题，复现后会进行定位并修复。

**Comment by cyonjan** [comment]
建议你看看能否换个比较新的微信号（最好是新申请的）试一下，我看几个Hook程序都是在处理较新微信号的信息时出错的，应该新老微信号的个人信息组织和存储会有很大不同，有些Hook结果是取出的个人信息有特殊字符导致JSON解析错误316，也有报内存存取越界导致微信崩溃的。我昨天出问题的点就是换了个新微信号之后开始崩溃的，今天把微信存储信息清空再试，老号没问题，新号依旧崩溃（错误log文件和昨天描述一致）。
[WeChat218bd4.txt](https://github.com/ljc545w/ComWeChatRobot/files/9475589/WeChat218bd4.txt)

**Comment by ljc545w** [comment]
wxid之前有出现这种问题，用户可自行定义的微信号倒是没遇见过这种情况。

**Comment by pandalid** [comment]
我也遇到了相同问题，点击确定后微信自动升级了3.7.6，然后就无法使用了

**Comment by September999999999** [comment]
> 最好提供下崩溃时在进行的操作，这样不好判断是哪个接口导致的。还有，再崩溃的时候不要勾选发送错误报告。。这是在告诉tx你在使用插件。

我最近测试了多种场景发现,在连发引用消息的时候会崩溃,最近一次测试这个操作稳定崩溃
![image](https://user-images.githubusercontent.com/32701871/192697757-bfc107c5-e7f4-41f6-96a2-3d6915f6d1b3.png)
