### ISSUE TITLE
请问有没有一种方式可以获取到”发送者撤回了一条消息“这个事件

### ISSUE THREAD

**Issue by tmsdy** [ljc545w/ComWeChatRobot#103]

**Comment by ljc545w** [comment]
目前没有防撤回功能，撤回消息类型，没记错的话，是10000

**Comment by tmsdy** [comment]
不是需要防撤回功能，我打印了所有的消息，但是在遇到有人撤回的时候，没有输出任何消息

**Comment by ljc545w** [comment]
试了下现在确实获取不到，我再找一下Hook位置。

**Comment by tmsdy** [comment]
https://github.com/huiyadanli/RevokeMsgPatcher

看这个项目能否帮助大佬节省时间

**Comment by ljc545w** [comment]
#110 已经可以获取到撤回消息提示。

**Comment by tmsdy** [comment]
谢谢大佬，测试OK
