### ISSUE TITLE
读取群列表不完整

### ISSUE THREAD

**Issue by cyonjan** [ljc545w/ComWeChatRobot#104]
WECHAT_CONTACT_GET_LIST读出的群列表不完整，只列出了活跃在微信PC中的前N项（补丁）记录，手动操作后活跃的群又可以到列表中。不知是否有办法每次读出所有群列表？

**Comment by ljc545w** [comment]
没有加载进内存就没办法了，建议使用数据库查吧，过滤一下。`MicroMsg.db`，`Contact表`。

**Comment by cyonjan** [comment]
是的，这个问题是通病，也可在应用层面做，每次遇到@chatroom消息作判断，然后确定是否刷新群列表。
