### ISSUE TITLE
结构体 struct DbInfoStruct 编译不通过报错

### ISSUE THREAD

**Issue by shangdev** [ljc545w/ComWeChatRobot#11]
如图：
```
struct DbInfoStruct {
    DWORD handle;
    wchar_t* dbname;
    DWORD l_dbname;
    vector<TableInfoStruct> tables;
    DWORD count;
};
```
![image](https://user-images.githubusercontent.com/15621520/165032921-ca3c4918-8ef9-4a4c-8ae9-eafcdcceabba.png)

这个是哪里出问题了吗？

**Comment by ljc545w** [comment]
结构体中包含vector，在声明前必须`#include<vector>`，标头要引入完整。

**Comment by shangdev** [comment]
还需要 `using namespace std;`
