### ISSUE TITLE
WECHAT_CONTACT_SEARCH_BY_CACHE 返回的 wxBigAvatar 和 wxSmallAvatar 都为 null

### ISSUE THREAD

**Issue by duo** [ljc545w/ComWeChatRobot#111]
调用HTTP (type=18) 接口返回 wxBigAvatar 和 wxSmallAvatar 都为 null
调用HTTP (type=34) 接口查询 Contact 表, 发现数据库里的所有记录的 BigHeadImgUrl 和 SmallHeadImgUrl 也为空值

但是客户端里是有头像的，不知道是什么原因

**Comment by ljc545w** [comment]
第一个，因为url相对来说数据太大，只有需要的时候才会加载进内存。
第二个，头像在另外一张表里，需要关联查询。

**Comment by duo** [comment]
> 第一个，因为url相对来说数据太大，只有需要的时候才会加载进内存。 第二个，头像在另外一张表里，需要关联查询。

多谢多谢，和 ContactHeadImgUrl 关联起来解决了
目前看来走 WECHAT_CONTACT_SEARCH_BY_CACHE 相对来说局限性蛮大的，联系人相关的我还是走数据库查询吧
