### ISSUE TITLE
发送消息成功后返回 msgid 和 localId

### ISSUE THREAD

**Issue by duo** [ljc545w/ComWeChatRobot#114]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [x] 添加新的功能
- [ ] 请求技术支持

----
**功能**

希望发送消息的接口成功后能返回 msgid 和 localId

**Comment by ljc545w** [comment]
这个不好加，需要搞很多hook点，也影响效率。
