### ISSUE TITLE
想请大佬喝杯茶

### ISSUE THREAD

**Issue by tmsdy** [ljc545w/ComWeChatRobot#117]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [ x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ x] BUG 反馈或建议
- [ ] 添加新的功能
- [ ] 请求技术支持

请大佬把收款码帖出来，想请大佬喝杯茶

**Comment by ljc545w** [comment]
好意心领了，暂时还能用爱发电，发不动的时候就放收款码了，哈哈

**Comment by tmsdy** [comment]
发不动的时候一定要说出来啊~
