### ISSUE TITLE
登录二维码字符串

### ISSUE THREAD

**Issue by oooooos** [ljc545w/ComWeChatRobot#119]
**我确定我已经查看了** (标注`[x]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [ ] 添加新的功能
- [x] 请求技术支持

请问获取到的登录二维码字符串是base64 ,我该以什么方式获取二维码图片

![image](https://user-images.githubusercontent.com/56820459/191214940-3940ca05-ba41-4ac1-a87b-5b59eb375944.png)

**Comment by duo** [comment]
这个不是base64哈，就是PNG图片的原始byte
