### ISSUE TITLE
[功能增加]大佬，能添加一个转发视频号的功能嘛，自己视频号的功能想转发到群里供大家学习使用。

### ISSUE THREAD

**Issue by liujingyangself** [ljc545w/ComWeChatRobot#122]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [ ] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [ ] 添加新的功能
- [ ] 请求技术支持

**Comment by tmsdy** [comment]
目前的版本  转发消息接口 是可以直接转发视频号的内容的。
