### ISSUE TITLE
求一个发送原始XML数据或者发送小程序转发信息的功能，谢谢大佬！

### ISSUE THREAD

**Issue by wymjeef** [ljc545w/ComWeChatRobot#126]
才接触VS，不熟悉，问了个小白问题，编辑掉了！
后面跟了一个编辑前的尾巴也不知道怎么删除掉。
最后再说一句，谢谢[ljc545w]大佬的分享精神。

**Comment by wymjeef** [comment]
我尝试过把#define USE_COM中的#define USE_COM修改成#define USE_SOCKET，结果很多函数都参数错误了

**Comment by ljc545w** [comment]
有些宏是加在编译命令里的，所以是要改解决方案配置。  
原始xml是有考虑加的，请耐心等待

**Comment by wymjeef** [comment]
谢谢你的回复，再请问下，普通网页文章之类的信息发送标识是5，小程序信息好像是21。
我可否用已有的这个“发送文章”的接口，修改发送标识为"21"，再定义xml内容为小程序的数据信息，达到发送小程序信息的目的，它们的发送流程是一样的吗？

**Comment by ljc545w** [comment]
如果只是为了发送小程序，拿到gh开头的小程序id，然后可以调用一个专用的接口去发送。

**Comment by wymjeef** [comment]
> 如果只是为了发送小程序，拿到gh开头的小程序id，然后可以调用一个专用的接口去发送。

期待大佬的更新，我先按我的思路试一下!

**Comment by ljc545w** [comment]
#132

**Comment by wymjeef** [comment]
> #132

谢谢大佬，马上测试！

**Comment by wymjeef** [comment]
发送xml消息的图片处理有点问题，对方收到后不显示图片，发送端能显示，消息json里有图片的本地路径信息。

**Comment by luochaolun** [comment]
> 发送xml消息的图片处理有点问题，对方收到后不显示图片，发送端能显示，消息json里有图片的本地路径信息。

能否发个可以发小程序的xml消息呢，里边都有什么参数？谢谢了！
