### ISSUE TITLE
增加群聊头像的及时刷新功能，这个是否有可能

### ISSUE THREAD

**Issue by feather8013** [ljc545w/ComWeChatRobot#128]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [x] 添加新的功能
- [ ] 请求技术支持

如题，增加群聊头像的及时刷新功能

**Comment by ljc545w** [comment]
这个是做什么用呢
