### ISSUE TITLE
检测好友变为了加好友

### ISSUE THREAD

**Issue by Kerwin1202** [ljc545w/ComWeChatRobot#13]
我用的今天最新版本，调用 CCheckFriendStatus 结果每调用一次都出现了加好有提示，是否是 3.7 适配的问题
![image](https://user-images.githubusercontent.com/16319833/171660571-c04bed78-0f79-41b6-9a8c-4117f968080f.png)

**Comment by Kerwin1202** [comment]
c# 的例子中 `FriendList`  应该是  `FriendList[i, 1, 1]` 才对，`FriendList[i, 0, 1]` 看上去是没修改过以前的微信号

**Comment by ljc545w** [comment]
> 1. 是否有回调的接收消息案例 （C#) 目前我是 while 循环获取
> 2. 是否考虑增加 `CReceiveMessage` 获取自己的消息，目前自己发的消息不被接收( 如果用来备份聊天记录)

C#我搞不明白，其实能写出来一个例子就不错了T_T。至于自己的消息，上个版本的hook点能同时hook到发送和接收，这个版本暂时没找到同样的Hook点。后续再加一个吧

**Comment by Kerwin1202** [comment]
59e2bc9a176c337bf7cacc389361dcef.dat 接收到图片消息是否有解密方法，否则无法预览或二次转发

**Comment by ljc545w** [comment]
> 59e2bc9a176c337bf7cacc389361dcef.dat 接收到图片消息是否有解密方法，否则无法预览或二次转发

异或加密，很简单，拿前两个字节跟0xffd8、0x8950之类的做一下异或，一样的话就是密钥，直接异或整张图片，再保存。

**Comment by ljc545w** [comment]
> > > 我用的今天最新版本，调用 CCheckFriendStatus 结果每调用一次都出现了加好有提示，是否是 3.7 适配的问题 ![image](https://user-images.githubusercontent.com/16319833/171660571-c04bed78-0f79-41b6-9a8c-4117f968080f.png)
> > 
> > 
> > 非也，你可以拿小号测试一下，一般对方不会收到提示，除非对方设置了免验证（这种情况非好友会直接添加成功）。
> 
> 主要有点怪 跑了一遍多了一个消息还给所有人都拉上来了，类似几千人的话都跑一遍，就找不到刚刚聊天的人了，
> 
> 这个提示可能待验证，我之前是遇到过，我同意过人，然后对方把我删了，他在把我加上（这时候没同意请求直接同意），我会收到消息
> 
> ![image](https://user-images.githubusercontent.com/16319833/171675012-7ec4a85d-6141-4f71-a5f1-a8c6b76d71c3.png)
对方删了你，他还在你好友列表里，本身就是可以直接添加你的。你调用接口就是为了找出这种好友，情况完全不一样的。

**Comment by Kerwin1202** [comment]
CReceiveMessage 是否考虑增加一个消息时间，否则有时候上次启动消息监听关闭了，但是下次打开 从方法里可以获取到很多消息，都是之前的，如果有给时间，可以自己过滤
