### ISSUE TITLE
邀请语音聊天和群聊语音聊天，增加通知信息

### ISSUE THREAD

**Issue by QQ-War** [ljc545w/ComWeChatRobot#131]
- [ ] 添加新的功能
邀请语音聊天和群聊语音聊天，增加通知信息，当前的信息没有更多的信息，谁邀请的，参加语音还是视频聊天的。

**Comment by ljc545w** [comment]
晚点看看，现在是能收到提醒的，只是缺少详细信息对吧？

**Comment by QQ-War** [comment]
嗯，现在
1.群里面的语音通话应该是没提醒。
2.私聊的语音通话，没有带信息，包括是谁播过来的这些。

**Comment by ljc545w** [comment]
#141

**Comment by QQ-War** [comment]
试用了下，还有一点点问题。就是群聊的语音，如果群里其他人拉会，没有邀请你入会的话，是没有收到通知的。
这个可能看下怎么优化。

**Comment by ljc545w** [comment]
> 试用了下，还有一点点问题。就是群聊的语音，如果群里其他人拉会，没有邀请你入会的话，是没有收到通知的。 这个可能看下怎么优化。

我觉得这样是正常的，就先这样吧。
