### ISSUE TITLE
在电脑端发送消息  isSendByPhone 的值为1

### ISSUE THREAD

**Issue by xnxin** [ljc545w/ComWeChatRobot#135]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [X] BUG 反馈或建议
- [ ] 添加新的功能
- [ ] 请求技术支持

微信号比较老，之前修改过微信号，微信号不是 wxid 开头的。在 windows 的微信上发送消息，
`isSendByPhone = 1`
 但实际应该是
`isSendByPhone = 0`

**Comment by ljc545w** [comment]
可能需要你再做点别的测试。
1、换一个微信发消息，看返回是否正常
2、手机发送消息，观察电脑端显示是否仍然为1

**Comment by xnxin** [comment]
1. 另外一个比较新的微信电脑发送返回值正常
2. 手机端发送数据  `isSendByPhone = 1`

```json
{'extrainfo': '<msgsource>\n\t<signature>v1_jIpjxNF6</signature>\n</msgsource>\n', 'filepath': '', 'isSendByPhone': 1, 'isSendMsg': 1, 'message': 'phone', 'msgid': 6534045652968949270, 'pid': 32, 'self': 'huaxxxxx', 'sender': 'wxid_xxxxxxxxx', 'sign': 'cd17b693fbcfaa8171c96f3cfcbf4f7f', 'thumb_path': '', 'time': '2022-10-12 09:37:28', 'timestamp': 1665563848, 'type': 'text', 'wxid': 'wxid_xxxxxxxxx'}
```

**Comment by ljc545w** [comment]
#141
