### ISSUE TITLE
不会自动下载视频

### ISSUE THREAD

**Issue by 0honus0** [ljc545w/ComWeChatRobot#136]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈或建议
- [x] 添加新的功能
- [ ] 请求技术支持

这边是在docker里面用的最新版的0.0.8版本
存在接收到视频不自动下载的问题

另外可以提供一个发送动态表情的接口吗？发送图片和文件接口都不符合这个情况

**Comment by ljc545w** [comment]
忘了你这里面还有个发表情的issue，下次吧

**Comment by 0honus0** [comment]
好的

**Comment by 0honus0** [comment]
还有发送图片怎么发送原图

**Comment by ljc545w** [comment]
啊这，如果是微信自动压缩的，那就没办法（折中的办法是走文件接口）。

**Comment by 0honus0** [comment]
> 啊这，如果是微信自动压缩的，那就没办法（折中的办法是走文件接口）。

就微信发送图片可以选择原图这个参数，不知道接口可不可以提供

**Comment by ljc545w** [comment]
发送原图这个选项电脑端没有啊

**Comment by 0honus0** [comment]
> 发送原图这个选项电脑端没有啊

哦，是这样啊

**Comment by 0honus0** [comment]
测试还发现个别发送或者接收的图片不会自动下载，只有个预览图，点开才会下载，在消息上报的路径中才能找到对应文件
可能与时间有关，一天中有个别时间段会出现这种情况，这个只是猜测，没具体测试过

**Comment by 0honus0** [comment]
晚上这个时间就会一直下载失败

**Comment by ljc545w** [comment]
#159

**Comment by 0honus0** [comment]
这边测试暂时没遇到下载失败的问题了
