### ISSUE TITLE
好友列表的判断问题

### ISSUE THREAD

**Issue by SupernovaCooper** [ljc545w/ComWeChatRobot#137]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈或建议
- [ ] 添加新的功能
- [ ] 请求技术支持

感谢大佬的作品。

看wxRobot.py中的好友判断逻辑是  if 'wxid_' == item['wxid'][0:5]: 不知道是不是意思就是 开头5个字符是 wxid_ 则认为是好友，但是实际上发现有些好友的wxid并不是wxid_开头，所以这里的判断可能会导致漏掉好多好友。所以demo里取出好友列表、公众号列表的方法可能都不准确。希望大佬研究下，谢谢。

**Comment by ljc545w** [comment]
这个我以前记得要改来着，给忘了。下次我看看能不能解决，你先从数据库里查一下，`select a.UserName as `wxID`,a.Alias as `微信号`,a.EncryptUserName as `V3数据`,a.Type as `联系人类型`,a.VerifyFlag as `添加方式`,a.Remark as `备注`,a.NickName as `昵称`,b.bigHeadImgUrl as `头像`,a.ExtraBuf as `扩展数据`  from Contact a inner join ContactHeadImgUrl b where a.UserName=b.usrName and a.Type=3;`，库是`MicroMsg.db`
