### ISSUE TITLE
新功能：与红包 和收付款相关的接口

### ISSUE THREAD

**Issue by xuxin1** [ljc545w/ComWeChatRobot#138]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [x] 添加新的功能
- [ ] 请求技术支持

# 后去会添加红包，或者收付款借口吗？

**Comment by ljc545w** [comment]
Windows微信只有红包提醒，没有红包功能；收款在做，付款就算了吧，就算Windows支持也没法弄。

**Comment by ljc545w** [comment]
#141
