### ISSUE TITLE
大佬 CGetChatRoomMembers 能搞个也返回json的方法吗？

### ISSUE THREAD

**Issue by SupernovaCooper** [ljc545w/ComWeChatRobot#139]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈或建议
- [x] 添加新的功能
- [ ] 请求技术支持

感谢大佬的作品。

大佬 CGetChatRoomMembers 能搞个也返回json的方法吗？用易语言接收到的变体型解析出来的list顺序都乱套（貌似多维数组都变成了一维数组，太麻烦了不会玩）啦。。

**Comment by ljc545w** [comment]
这个接口我看了下，就是一个2x2的数组。
简化倒是简单，但是还要跟以前版本做兼容
你还是再想想办法吧，这个目录下的代码或许能帮到你
https://github.com/ljc545w/ComWeChatRobot/tree/master/old_projects/ESDK

**Comment by SupernovaCooper** [comment]
这里面的代码我看了，API不全，没有变体型参数的相关处理。
我之前的描述不准确，不是二维数组变成了一维数组，而是{{key1,value1},{key2,value2}}变成了{key1,key2,value1,value2}
我自己虽然通过其他方式解析了出来，但是很不科学，数组数量/2然后再一一对应。。。除了这个方式没找到其他更科学的方法。所有返回变体型的API都面临这个问题。这应该是易语言的问题。

如果不能提供新API，那目前只能用这种办法了。。。好尴尬。
