### ISSUE TITLE
请求技术支持

### ISSUE THREAD

**Issue by zhanghehua** [ljc545w/ComWeChatRobot#142]
<!--
**我确定我已经查看了** (标注`[ ]`为`[x]`)
----

**我要申请**  (标注`[ ]`为`[x]`)
- [ ] 请求技术支持

![微信图片_20221017134722](https://user-images.githubusercontent.com/50280856/196099343-799ca728-a9de-4dd8-bc6a-48a1dd895212.png)
这是为什么，com我也安装了，dll也引用了，项目里的实例，启动服务都要传参数pid，所有的接口都要传pid

**Comment by zhanghehua** [comment]
![微信图片_20221017134722](https://user-images.githubusercontent.com/50280856/196099502-4f2bc04f-a617-4e86-bfea-bd4107a88ab9.png)

**Comment by zhanghehua** [comment]
dll也引用了，com也安装了，启动服务就失败，项目实例，现在不知道为什么需要传pid，每个接口都需要传pid了

**Comment by SupernovaCooper** [comment]
传pid是为了支持多进程啊。有多个wx实例，只能通过pid来区分你最终要操作的进程（哪个wx账户）啊。

**Comment by zhanghehua** [comment]
> 传pid是为了支持多进程啊。有多个wx实例，只能通过pid来区分你最终要操作的进程（哪个wx账户）啊。

pid问题懂了，你能看下图片为什么服务起不来吗，我找个dll不知道为什么不需要传pid--是因为版本低吗

**Comment by zhanghehua** [comment]
我单独引用DLL文件Interop.WeChatRobotCOMLib.dll无法使用，但在实例里，就可以用，我另起一个项目，单独引用DLL，会报错

**Comment by ljc545w** [comment]
旧版本不支持多开管理，所以不需要pid，全面支持多开管理后，com版本使用pid，http版本使用端口。
