### ISSUE TITLE
test.py运行出错

### ISSUE THREAD

**Issue by hankssr** [ljc545w/ComWeChatRobot#145]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x ] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x ] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [ ] 添加新的功能
- [x ] 请求技术支持

运行test.py文件出错,已经完成安装
<img width="620" alt="1666147148069" src="https://user-images.githubusercontent.com/103753924/196584854-166cb4e0-c5d9-4b49-b7d6-3b6fb2a79523.png">

求助问题在哪里?
还有请问完成安装和卸载是否有提示信息?我安装完未出现提示信息,是否表示安装成功?

**Comment by ljc545w** [comment]
换版本的话，要先执行一遍`CWeChatRobot.exe unregserver`，然后找到comtypes包下的gen目录，删除里面的缓存文件，再重新注册即可。没有提示信息就是正常的，有提示信息就是报错了。

**Comment by hankssr** [comment]
搞定了,谢谢大佬:=}
