### ISSUE TITLE
修改历史记录的话，是不是SQL命令直接修改

### ISSUE THREAD

**Issue by monkeycc** [ljc545w/ComWeChatRobot#146]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [ ] 添加新的功能
- [x] 请求技术支持

---------------
修改聊天历史记录的话，是不是SQL命令直接修改,还是需要提取数据库，修改，再覆盖

**Comment by tmsdy** [comment]
SQL命令直接修改就可以了

**Comment by monkeycc** [comment]
大佬,Python求SQL命令演示
@tmsdy

**Comment by tmsdy** [comment]
![image](https://user-images.githubusercontent.com/12005139/197102960-5248667c-61bb-44d6-a862-5306d73ca16e.png)
我这个是把一条消息改成另一条消息。
