### ISSUE TITLE
Python 聊天记录怎么导出,导出的MicroMsg.db并没有包含聊天记录

### ISSUE THREAD

**Issue by monkeycc** [ljc545w/ComWeChatRobot#149]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [ ] 添加新的功能
- [x] 请求技术支持

---------------

Python 聊天记录怎么导出
```
def test_BackupDb(instance):
    try:
        dbs = instance.GetDbHandles()
        dbname = 'MicroMsg.db'
        handle = dbs.get(dbname).get('Handle')
        rc = instance.BackupSQLiteDB(handle, 'D:\\ComWeChatRobot-master\\Python\\com\\{}'.format(dbname))
        print(rc)
    except Exception as e:
        print(e)
```
导出的MicroMsg.db并没有包含聊天记录

**Comment by ljc545w** [comment]
MSGx.db，x是一个数字

**Comment by monkeycc** [comment]
微信数据目录
\Msg\MicroMsg.db
\Msg\Multi\MSG0.db

我发现应该是要写MSG0.db
dbname = 'MSG0.db'

但是python导出的时候 报错
```
        dbname = 'MicroMsg.db'
        handle = dbs.get(dbname).get('Handle')
```
'NoneType' object has no attribute 'get'

**Comment by ljc545w** [comment]
稍等，晚点发布

**Comment by ljc545w** [comment]
#150
