### ISSUE TITLE
请问调试出错后，没有StopService，就无法获取数据了

### ISSUE THREAD

**Issue by cluic** [ljc545w/ComWeChatRobot#15]
大佬您好，请问一下调试出错后脚本自动关闭，没有StopService的话，再次StartService就无法获取微信数据，这个怎么办呢，除了退出微信重新登陆，还有别的办法吗？
非常感谢~

**Comment by ljc545w** [comment]
> 大佬您好，请问一下调试出错后脚本自动关闭，没有StopService的话，再次StartService就无法获取微信数据，这个怎么办呢，除了退出微信重新登陆，还有别的办法吗？ 非常感谢~

今天对启动和退出两个接口做了下简单优化，脚本可以先调用一次StopService再StartService，如果有问题可以再反馈，因为这个东西我也不是一直用，有些问题发现不了。

**Comment by cluic** [comment]
感谢感谢，辛苦了
这个目前只有3.7做了这个优化嘛，3.6是不是还是不行

**Comment by ljc545w** [comment]
> 感谢感谢，辛苦了 这个目前只有3.7做了这个优化嘛，3.6是不是还是不行

3.6没有优化，稍晚点再弄

**Comment by cluic** [comment]
谢谢~

**Comment by ljc545w** [comment]
> 谢谢~

已经做了简单的修改，可以拉取试一下，如果有问题再告诉我~

**Comment by cluic** [comment]
> 

这么快，感谢感谢，请问需要重新下载替换文件吗

**Comment by ljc545w** [comment]
> > 
> 
> 这么快，感谢感谢，请问需要重新下载替换文件吗

是的，也可以git pull重新拉取3.6.0.18这个分支
