### ISSUE TITLE
发送文章消息，图片200kb左右，消息出现 红色感叹号，无法发出

### ISSUE THREAD

**Issue by thelosttimes** [ljc545w/ComWeChatRobot#155]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈或建议
- [ ] 添加新的功能
- [ ] 请求技术支持

发送文章，图片200kb左右，消息发送出现 红色感叹号

**Comment by ljc545w** [comment]
用个小点的吧，本身也是缩略图。还有，那个图片可能别人看不到，未来考虑取消这个参数。可以尝试使用发原始xml的接口。
