### ISSUE TITLE
群聊公告设置存在乱码的情况。

### ISSUE THREAD

**Issue by feather8013** [ljc545w/ComWeChatRobot#158]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈或建议
- [ ] 添加新的功能
- [ ] 请求技术支持

群聊公告设置存在乱码的情况。

**Comment by ljc545w** [comment]
已复现到一次问题，该接口过于麻烦，暂时没有精力修复。

**Comment by feather8013** [comment]
影响不大
