### ISSUE TITLE
请教一下检查是否被好友删除原理

### ISSUE THREAD

**Issue by digjack** [ljc545w/ComWeChatRobot#167]
你好，想请教一下  WECHAT_CONTACT_CHECK_STATUS 检查是否被好友删除，是基于什么原理么，会打扰用户么，这边模拟了下貌似是把所有的微信好友重新加过一遍， 一些对方已经删除的好友也重新加回来了，所以想确认一下。

**Comment by ljc545w** [comment]
对方没有设置验证的话，会直接添加成功，这种情况下有打扰，其他情况下暂时没发现打扰。
