### ISSUE TITLE
修改接口方式可行性

### ISSUE THREAD

**Issue by 0honus0** [ljc545w/ComWeChatRobot#17]
对c++这块不是特别熟悉，但之前在linux下发现COM接口无法使用
可以修改COM接口为websocket接口以方便在linux下运行hook提供接口吗

这种方式有可行性吗？

**Comment by ljc545w** [comment]
> 对c++这块不是特别熟悉，但之前在linux下发现COM接口无法使用 可以修改COM接口为websocket接口以方便在linux下运行hook提供接口吗
> 
> 这种方式有可行性吗？
这种实现还是挺多的，很多售卖DLL的，都是基于socket实现。不过我猜你想搞的是结合内网穿透的远程调用吧。
我这个项目做一些改动也可以适配websocket，不使用DLL里面的导出函数（就是包含Remote字样的）。
在DLL里面再写一套web接口实现信息交换、调用HOOK过程，其实也不难，但不好计算具体工作量。

**Comment by ljc545w** [comment]
> 对c++这块不是特别熟悉，但之前在linux下发现COM接口无法使用 可以修改COM接口为websocket接口以方便在linux下运行hook提供接口吗
> 
> 这种方式有可行性吗？
这种实现还是挺多的，很多售卖DLL的，都是基于socket实现。不过我猜你想搞的是结合内网穿透的远程调用吧。
我这个项目做一些改动也可以适配websocket，不使用DLL里面的导出函数（就是包含Remote字样的）。
在DLL里面再写一套web接口实现信息交换、调用HOOK过程，其实也不难，但不好计算具体工作量。

**Comment by 0honus0** [comment]
嗯，主要是做消息转发用的，但现在是拿一个单独的win运行微信hook作为接口，之前有一个docker-wechatPc 是用的ws提供的接口，可以使用wine运行在linux下。所以如果可以修改为ws的方式可以尝试做成docker，这样方便部署并且可以运行在一台服务器上

**Comment by ljc545w** [comment]
> 
改DWeChatRobot.dll就可以了，COM相关的可以直接不管，如果你用过C++的web库，很快应该就能搞定。
接口参数的数据结构并不复杂，基本都是wchar_t*。

**Comment by 0honus0** [comment]
没怎么用过，但如果不麻烦我可以试着修改下

**Comment by ljc545w** [comment]
> > > 没怎么用过，但如果不麻烦我可以试着修改下
> > 
> > 
> > 我改的话可能要等一段时间，还剩几个接口，以及3.7.0.29的适配。
> 
> 如果能帮忙改的话就很感谢了，我这段时间也在看相关资料，可以先试试，不行的话可能还要麻烦你了 还有就是微信发送语音的功能实现难度大吗

发语音没研究过，因为很少有用这个的。

**Comment by 0honus0** [comment]
> > > > 没怎么用过，但如果不麻烦我可以试着修改下
> > > 
> > > 
> > > 我改的话可能要等一段时间，还剩几个接口，以及3.7.0.29的适配。
> > 
> > 
> > 如果能帮忙改的话就很感谢了，我这段时间也在看相关资料，可以先试试，不行的话可能还要麻烦你了 还有就是微信发送语音的功能实现难度大吗
> 
> 发语音没研究过，因为很少有用这个的。

因为现在用的转发程序是基于[ehForwarderBot](https://github.com/ehForwarderBot/ehForwarderBot) 这个项目实现的，这个项目支持语音的收发，所以能实现是最好的

**Comment by ljc545w** [comment]
> > > > > 没怎么用过，但如果不麻烦我可以试着修改下
> > > > 
> > > > 
> > > > 我改的话可能要等一段时间，还剩几个接口，以及3.7.0.29的适配。
> > > 
> > > 
> > > 如果能帮忙改的话就很感谢了，我这段时间也在看相关资料，可以先试试，不行的话可能还要麻烦你了 还有就是微信发送语音的功能实现难度大吗
> > 
> > 
> > 发语音没研究过，因为很少有用这个的。
> 
> 因为现在用的转发程序是基于[ehForwarderBot](https://github.com/ehForwarderBot/ehForwarderBot) 这个项目实现的，这个项目支持语音的收发，所以能实现是最好的

Windows微信不支持发语音，甚至不支持转发语音，Hook语音的已经有了，考虑以文件形式代替吧。

**Comment by 0honus0** [comment]
> > > > > > 没怎么用过，但如果不麻烦我可以试着修改下
> > > > > 
> > > > > 
> > > > > 我改的话可能要等一段时间，还剩几个接口，以及3.7.0.29的适配。
> > > > 
> > > > 
> > > > 如果能帮忙改的话就很感谢了，我这段时间也在看相关资料，可以先试试，不行的话可能还要麻烦你了 还有就是微信发送语音的功能实现难度大吗
> > > 
> > > 
> > > 发语音没研究过，因为很少有用这个的。
> > 
> > 
> > 因为现在用的转发程序是基于[ehForwarderBot](https://github.com/ehForwarderBot/ehForwarderBot) 这个项目实现的，这个项目支持语音的收发，所以能实现是最好的
> 
> Windows微信不支持发语音，甚至不支持转发语音，Hook语音的已经有了，考虑以文件形式代替吧。

好吧

**Comment by ljc545w** [comment]
已提供http支持。

**Comment by 0honus0** [comment]
我看了下是通过python加载外部库的方式进行启动停止的，因为考虑在wine里面运行注入，在linux上运行python，所以可以在注入dll之后直接start_listen吗？把ctype这个python库去除，这个库跨平台会有各种问题
最后就是python直接通过http接口操作就行了

**Comment by ljc545w** [comment]
那个你得自己改，把http_start放到dllmain中去，重新编译就行了。

**Comment by 0honus0** [comment]
> 那个你得自己改，把http_start放到dllmain中去，重新编译就行了。

我可以试一下，那注入这个dll用哪个exe？

**Comment by ljc545w** [comment]
你也可以写个Windows程序，调用wxDriver中的导出函数的，提供pid和端口，就可以注入。

**Comment by ljc545w** [comment]
类似`wxDriver.exe -pid 1111 -port 2222`  
wxDriver.exe要根据pid找到微信进程，然后调用start_listen启动监听  
这样就不需要改SWeChatRobot.dll，也可以脱离ctypes

**Comment by 0honus0** [comment]
> 类似`wxDriver.exe -pid 1111 -port 2222` wxDriver.exe要根据pid找到微信进程，然后调用start_listen启动监听 这样就不需要改SWeChatRobot.dll，也可以脱离ctypes

可以，我尝试一下
