### ISSUE TITLE
请问一下各位大佬获取用户名需要加多少

### ISSUE THREAD

**Issue by rong888i** [ljc545w/ComWeChatRobot#178]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [ ] 添加新的功能
- [x] 请求技术支持

请问一下各位大佬获取name需要加多少
![1671262049371](https://user-images.githubusercontent.com/75567132/208230907-56875449-c7df-421c-8264-854d998e96e0.png)

**Comment by ljc545w** [comment]
消息结构里面没有昵称，需要使用wxid从数据库读取。
