### ISSUE TITLE
请教收款功能参数的含义

### ISSUE THREAD

**Issue by KunJZ** [ljc545w/ComWeChatRobot#179]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [ ] 添加新的功能
- [x] 请求技术支持

请问收款功能中的wxid，transcationid，transferid三个入参的含义分别代表什么呢？
<img width="824" alt="image" src="https://user-images.githubusercontent.com/49372092/210963356-7fa83ea8-8d79-438f-bd29-63cc8d41cffd.png">

**Comment by ljc545w** [comment]
从转账消息的xml中获取
