### ISSUE TITLE
正在学习，但是好像没起作用

### ISSUE THREAD

**Issue by QiGuaiDeDiDi** [ljc545w/ComWeChatRobot#18]
用的python
微信版本是3.6.0.18
根据您的提示，注册了COM组件，方法是管理员运行CMD，CD到Release目录，执行【CWeChatRobot.exe /regserver】命令
python的代码如下：

robot = comtypes.client.CreateObject("WeChatRobot.CWeChatRobot")
print(robot.CGetSelfInfo())

输出的是一个空的dict，也就是输出的是：{}
不知道我做的对不对，请指教

**Comment by hankssr** [comment]
要先实例化

**Comment by ljc545w** [comment]
> 用的python 微信版本是3.6.0.18 根据您的提示，注册了COM组件，方法是管理员运行CMD，CD到Release目录，执行【CWeChatRobot.exe /regserver】命令 python的代码如下：
> 
> robot = comtypes.client.CreateObject("WeChatRobot.CWeChatRobot") print(robot.CGetSelfInfo())
> 
> 输出的是一个空的dict，也就是输出的是：{} 不知道我做的对不对，请指教

需要先调用CStartService，在执行此操作前DLL不会注入 ，大多数接口也就无效。
