### ISSUE TITLE
cdn下载

### ISSUE THREAD

**Issue by wttnb911** [ljc545w/ComWeChatRobot#181]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [ ] 添加新的功能
- [x] 请求技术支持

你好，我想问下cdn图片视频下载是用解密出url直接请求下载吗？还是解密本地缓存dat文件？

**Comment by ljc545w** [comment]
类似请求url（cgi-bin这种），过程都是微信内部完成的
