### ISSUE TITLE
添加群成员失败，不知道什么原因？

### ISSUE THREAD

**Issue by luochaolun** [ljc545w/ComWeChatRobot#185]
- [ ] BUG 反馈或建议

添加群成员失败，不知道什么原因？一直返回{"msg":1,"result":"OK"}

**Comment by luochaolun** [comment]
是否超过40人的群，就加不了。

或者能否增加个“邀请好友进群”的功能呢？

**Comment by ljc545w** [comment]
Windows的限制，并不是加功能就能绕过的。
