### ISSUE TITLE
建议：能否增加“邀请好友进群”的功能？

### ISSUE THREAD

**Issue by luochaolun** [ljc545w/ComWeChatRobot#186]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [ ] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [x]添加新的功能
- [x] 请求技术支持
微信群超过200人，没法发二维码邀请好友进群，能否增加一个邀请好友进群的功能！

**Comment by ljc545w** [comment]
暂时没有添加新功能的计划。
