### ISSUE TITLE
  def SendAtText(self,wxid:list or str or tuple,msg):

### ISSUE THREAD

**Issue by hankssr** [ljc545w/ComWeChatRobot#19]
请问这个函数是什么作用呀?
感觉好像是在群聊里发送消息,但是我执行了完全没反应.

**Comment by hankssr** [comment]
我运行后发现是单独对群里成员发送信息,但是我想实现在群里群发或者单独@用户发送消息,这个可以实现吗?:=)

**Comment by ljc545w** [comment]
> 我运行后发现是单独对群里成员发送信息,但是我想实现在群里群发或者单独@用户发送消息,这个可以实现吗?:=)

SendAtText就是发送艾特消息用的。wxid是要艾特的人，可以是列表，也可以是单个wxid字符串。
