### ISSUE TITLE
大佬能否增加新功能？

### ISSUE THREAD

**Issue by xiaohan13145200** [ljc545w/ComWeChatRobot#190]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [x] 添加新的功能
- [ ] 请求技术支持

能否增加群里发送图片、视频、文件功能？

**Comment by ljc545w** [comment]
wxid填群聊的id就可以了啊
