### ISSUE TITLE
原始xml发送消息确实有问题，测试了3天，发个简单的位置消息也发不出去！

### ISSUE THREAD

**Issue by luochaolun** [ljc545w/ComWeChatRobot#191]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [x] BUG 反馈或建议
- [x] 添加新的功能
- [x] 请求技术支持

使用的位置xml为

<?xml version=\"1.0\"?><msg><location x=\"29.789783\" y=\"121.574013\" scale=\"15\" label=\"鄞州区万卷路\" maptype=\"0\" poiname=\"中海国际社区65幢(宁波市鄞州区)\" poiid=\"\" buildingId=\"\" floorName=\"\" /></msg>

不管是去掉<?xml version=\"1.0\"?>，还是不去掉
也不管是双引号转义还是不转义，都试过了，都发不出去！

折腾了几天了，也没成功，哪位测试成功了，给个xml示例吧！

**Comment by ljc545w** [comment]
把你收到的消息，用windows微信转发一下，这个xml才是能用Windows发出去的。此外，位置消息不是Windows支持的类型，只可以转发。

**Comment by ljc545w** [comment]
<msg>
    <fromusername>wxid_xxxxx</fromusername>
    <scene>0</scene>
    <commenturl></commenturl>
    <appmsg appid="" sdkver="0">
        <title>CSDN热榜</title>
        <des></des>
        <action>view</action>
        <type>33</type>
        <showtype>0</showtype>
        <content></content>
        <url>https://mp.weixin.qq.com/mp/waerrpage?appid=wx2115aba2ed1f96b9&amp;type=upgrade&amp;upgradetype=3#wechat_redirect</url>
        <dataurl></dataurl>
        <lowurl></lowurl>
        <lowdataurl></lowdataurl>
        <recorditem></recorditem>
        <thumburl></thumburl>
        <messageaction></messageaction>
        <md5>c53f1d581336066dbca7a8043f255053</md5>
        <extinfo></extinfo>
        <sourceusername>gh_3c26889f1a90@app</sourceusername>
        <sourcedisplayname>CSDN</sourcedisplayname>
        <commenturl></commenturl>
        <appattach>
            <totallen>0</totallen>
            <attachid></attachid>
            <emoticonmd5></emoticonmd5>
            <fileext>jpg</fileext>
            <filekey>a37c54a2effeb9ac7faa8e1a81b94324</filekey>
            <cdnthumburl>3057020100044b304902010002046a29cfca02032f59190204a3a66971020463e48b3a042466333338316238652d643732612d343834332d613232342d6333393039666135343136370204011800030201000405004c550500</cdnthumburl>
            <aeskey>e7e5e0decd8f1e3cad7b715df15154cb</aeskey>
            <cdnthumbaeskey>e7e5e0decd8f1e3cad7b715df15154cb</cdnthumbaeskey>
            <encryver>1</encryver>
            <cdnthumblength>31497</cdnthumblength>
            <cdnthumbheight>100</cdnthumbheight>
            <cdnthumbwidth>100</cdnthumbwidth>
        </appattach>
        <weappinfo>
            <pagepath>pages/hot-list/hot-list.html?tab=0</pagepath>
            <username>gh_3c26889f1a90@app</username>
            <appid>wx2115aba2ed1f96b9</appid>
            <version>92</version>
            <type>2</type>
            <weappiconurl>http://wx.qlogo.cn/mmhead/Q3auHgzwzM5WW4gTQibnE7KH7siblmyhib9RsVU1aood55GMpqfJbibic7g/96</weappiconurl>
            <appservicetype>0</appservicetype>
            <shareId>1_wx2115aba2ed1f96b9_12703c04c2f27d0f5513b5c0bfb948df_1675921950_0</shareId>
        </weappinfo>
        <websearch />
    </appmsg>
    <appinfo>
        <version>1</version>
        <appname>Window wechat</appname>
    </appinfo>
</msg>

**Comment by ljc545w** [comment]
消息太长了，显示不完整。自己弄吧，xml里的fromusername换成自己的。
