### ISSUE TITLE
好友状态检测报错

### ISSUE THREAD

**Issue by AStogov** [ljc545w/ComWeChatRobot#2]
使用python调用COM接口检测好友状态时，检测到一半会报keyError: 178 (0xB2)的错，估计是内存变化了？我本人不是很懂逆向，希望作者赐教。
微信版本是3.6.0.18，大概检测40个好友左右就报错了，还有这个好友检测貌似会把自己黑名单里的人一起检测。

**Comment by ljc545w** [comment]
这个是python的报错，我的通讯录里没有0xB2状态的好友，你帮忙确定一下，0xB2是自己拉黑了对方，还是别的情况，我加进去。

**Comment by AStogov** [comment]
显示为“被搜账号状态异常、无法显示”，应该是在黑名单里的被封号的用户



------------------&nbsp;Original&nbsp;------------------
From: "Jack ***@***.***&gt;; 
Date: 2022年3月26日(星期六) 下午5:25
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [ljc545w/ComWeChatRobot] 好友状态检测报错 (Issue #2)





 
这个是python的报错，我的通讯录里没有0xB2状态的好友，你帮忙确定一下，0xB2是自己拉黑了对方，还是别的情况，我加进去。

**Comment by ljc545w** [comment]
感谢，示例文件已更新
