### ISSUE TITLE
您好，又遇到新的问题了，获取不到消息

### ISSUE THREAD

**Issue by QiGuaiDeDiDi** [ljc545w/ComWeChatRobot#20]
微信版本：3.6.0.18
使用的python
代码如下：
robot = comtypes.client.CreateObject("WeChatRobot.CWeChatRobot")
robot.CStartRobotService()
myinfo = robot.CGetSelfInfo()
print(myinfo)
while True:
    message = robot.CReceiveMessage()
    print(message)

可以获取到myinfo，但是获取的message全是空的

**Comment by ljc545w** [comment]
> 微信版本：3.6.0.18 使用的python 代码如下： robot = comtypes.client.CreateObject("WeChatRobot.CWeChatRobot") robot.CStartRobotService() myinfo = robot.CGetSelfInfo() print(myinfo) while True: message = robot.CReceiveMessage() print(message)
> 
> 可以获取到myinfo，但是获取的message全是空的

请确认您已参考wxRobot.py和test.py中的调用。包含HOOK事件的，都需要先调用另外一个接口手动开启。

**Comment by ljc545w** [comment]
> 

麻烦按以下步骤定位下问题：
1、调用CStopRobotService彻底关闭COM
2、重启微信
3、调用CStartRobotService启动服务
4、调用CStartReceiveMessage，并观察返回值是否为0
5、如果上述返回值为0，用小号给PC发送一条消息，然后调用CReceiveMessage
6、如果返回值不为0，直接向我反馈即可
