### ISSUE TITLE
关于CRegisterWxPidWithCookie

### ISSUE THREAD

**Issue by peditding** [ljc545w/ComWeChatRobot#202]
请问在C#中如何接收消息？
wxEvent.OnGetMessageEvent += WxEvent_OnGetMessageEvent; // 不行

int c = wxEvent.CRegisterWxPidWithCookie((uint)pid, 1); // 这个函数如何使用？第二个参数cookie是啥？

**Comment by peditding** [comment]
我弄错了

**Comment by ctlyh3059** [comment]
C#使用COM你获得到消息吗？cookie你知道哪里来的值吗？
