### ISSUE TITLE
可以写一个c#的ReceiveMessage实例吗

### ISSUE THREAD

**Issue by pauljohn21** [ljc545w/ComWeChatRobot#23]
python的实例很全，能把c#的也补上吗，多谢

**Comment by ljc545w** [comment]
> python的实例很全，能把c#的也补上吗，多谢

那个C#还是别人补充的，我写可能会很费劲。其实就是先启动消息Hook，然后开启子线程去循环取消息（不过这个子线程必须调用CoInitialize才能正常使用API），其他的正常写就好。

**Comment by RingoStudio** [comment]
@pauljohn21 我刚发了我写的c#实现，你可以参考一下
[https://github.com/RingoStudio/ComWechatRobotCsharp](url)

**Comment by pauljohn21** [comment]
> RingoStudio

多谢
