### ISSUE TITLE
发现个问题，不支持线程中发送信息

### ISSUE THREAD

**Issue by QiGuaiDeDiDi** [ljc545w/ComWeChatRobot#24]
python代码如下：

def chu_li_msg(msg):
    global robot
    robot.CSendText('filehelper', msg)
robot = comtypes.client.CreateObject("WeChatRobot.CWeChatRobot")
status = robot.CStartRobotService()
print('ServiceStatus', status)
status = robot.CStartReceiveMessage()
while True:
    message = dict(robot.CReceiveMessage())
    if message:
        _thread.start_new_thread(chu_li_msg, (message['message'],))
    time.sleep(0.1)

执行后报错：
ctypes.COMError: (-2147221008, '尚未调用 CoInitialize。', (None, None, None, 0, None))

根据提示，调用CoInitialize后，报错：
_ctypes.COMError: (-2147417842, '应用程序调用一个已为另一线程整理的接口。', (None, None, None, 0, None))

**Comment by ljc545w** [comment]
你好，COM组件是支持在子线程中调用的。按照错误信息Google/Baidu即可。

**Comment by QiGuaiDeDiDi** [comment]
已解决！感谢！

**Comment by thelosttimes** [comment]
你好，请问怎么解决的呀，可以分享一下案例吗？感谢！
