### ISSUE TITLE
询问如何获取群成员昵称

### ISSUE THREAD

**Issue by RingoStudio** [ljc545w/ComWeChatRobot#26]
大佬你好。
目前我这边需要由用户A 发出带有“@B …”的指令，使bot识别并找到目标成员B。因此需要有“**获取群成员昵称**”的功能🥹

我尝试了执行SQL语句，
`“SELECT xx, MemberList, DisplayName FROM ChatRoom”`
在ChatRoom这个表中，成员wxid和成员昵称都是由“^G”连接的一整个字符串。
问题出现在这里，这两个字符串分割后的列表并不能一一对应。不知道大佬对此有无解决办法。

我看过其他bot的运行，另一位大佬的做法是按照chatroomid以及wxid查找昵称（见https://bbs.pediy.com/thread-258557.htm 

希望大佬可以完善这部分的功能，让bot更加完美。谢谢🙏

**Comment by ljc545w** [comment]
> 

看下MicroMsg.db，Contact这张表，联系人包括好友、群聊、群聊好友、公众号，小程序应该也有。
`select NickName from Contact where UserName="xxx"`，UserName是wxid
发艾特消息的时候只需要指定艾特的人的微信id就可以了，接口会自动把`@昵称`加到消息文本里
使用的是查询好友信息接口，这个接口的信息，猜测也是从数据库里取出来的。

**Comment by RingoStudio** [comment]
> 看下MicroMsg.db，Contact这张表，联系人包括好友、群聊、群聊好友、公众号，小程序应该也有。
> `select NickName from Contact where UserName="xxx"`，UserName是wxid
> 发艾特消息的时候只需要指定艾特的人的微信id就可以了，接口会自动把`@昵称`加到消息文本里
> 使用的是查询好友信息接口，这个接口的信息，猜测也是从数据库里取出来的。

谢谢大佬的回复！
在Contact表中可以取到所有群的成员的原本昵称，但是很可惜的是，这不是群昵称。

取到真实群昵称的一个重要的作用是：
当在下图这个场景中，bot接收到的消息里是仅包含“@群昵称”的，如果我只知道这个人的微信昵称，就找不到这个人了。
![898DC369-62B9-43A0-AF36-165B6403A880](https://user-images.githubusercontent.com/45715999/173201551-4a6b95c1-85ad-496c-b6cc-b71d76d85add.jpeg)

所以还想继续问问大佬有无更好的解决办法。
十分感谢。

**Comment by QiGuaiDeDiDi** [comment]
> > 看下MicroMsg.db，Contact这张表，联系人包括好友、群聊、群聊好友、公众号，小程序应该也有。
> > `select NickName from Contact where UserName="xxx"`，UserName是wxid
> > 发艾特消息的时候只需要指定艾特的人的微信id就可以了，接口会自动把`@昵称`加到消息文本里
> > 使用的是查询好友信息接口，这个接口的信息，猜测也是从数据库里取出来的。
> 
> 谢谢大佬的回复！ 在Contact表中可以取到所有群的成员的原本昵称，但是很可惜的是，这不是群昵称。
> 
> 取到真实群昵称的一个重要的作用是： 当在下图这个场景中，bot接收到的消息里是仅包含“@群昵称”的，如果我只知道这个人的微信昵称，就找不到这个人了。 ![898DC369-62B9-43A0-AF36-165B6403A880](https://user-images.githubusercontent.com/45715999/173201551-4a6b95c1-85ad-496c-b6cc-b71d76d85add.jpeg)
> 
> 所以还想继续问问大佬有无更好的解决办法。 十分感谢。

我记得获取的message中，有一个字段是被@的人的微信ID。通过ID绑定人员不久行了？

**Comment by QiGuaiDeDiDi** [comment]
我以前用过别人的hook，可以hook到被@的人的微信ID。不知道大佬能不能实现

**Comment by ljc545w** [comment]
> > 看下MicroMsg.db，Contact这张表，联系人包括好友、群聊、群聊好友、公众号，小程序应该也有。
> > `select NickName from Contact where UserName="xxx"`，UserName是wxid
> > 发艾特消息的时候只需要指定艾特的人的微信id就可以了，接口会自动把`@昵称`加到消息文本里
> > 使用的是查询好友信息接口，这个接口的信息，猜测也是从数据库里取出来的。
> 
> 谢谢大佬的回复！ 在Contact表中可以取到所有群的成员的原本昵称，但是很可惜的是，这不是群昵称。
> 
> 取到真实群昵称的一个重要的作用是： 当在下图这个场景中，bot接收到的消息里是仅包含“@群昵称”的，如果我只知道这个人的微信昵称，就找不到这个人了。 ![898DC369-62B9-43A0-AF36-165B6403A880](https://user-images.githubusercontent.com/45715999/173201551-4a6b95c1-85ad-496c-b6cc-b71d76d85add.jpeg)
> 
> 所以还想继续问问大佬有无更好的解决办法。 十分感谢。

需要在群内修改后的昵称啊，有空我找找

**Comment by ljc545w** [comment]
> 

这个没注意过，可能在扩展信息里有，懒得搞pb解析

**Comment by ljc545w** [comment]
@RingoStudio ChatRoom那张表，RoomData字段，按protobuf解析，就是群昵称和wxid的对应。数据库查询接口是支持Blob类型的。

**Comment by RingoStudio** [comment]
> 

谢谢大佬指点，这个我去研究一下😁有结果了回来说

**Comment by RingoStudio** [comment]
@ljc545w 大佬这个RoomData字段并不是标准的protobuf格式吧
`0x0A, 0x2C, 0x0A, 0x13, 0x77, 0x78, 0x69, 0x64, 0x5F, 0x79, 0x77, 0x67, 0x39, 0x74, 0x67, 0x64`
表中所有这个字段的第1、3个byte都是0A。

我又看了一下UserNameList和displayName的字段，如果按UserNameList作为索引，displayName顺序是对的，只是会跳过没有设置昵称的成员。

目前这个RoomData还没有看出门道。希望得到您的指点
感谢感谢。

**Comment by ljc545w** [comment]
> @ljc545w 大佬这个RoomData字段并不是标准的protobuf格式吧 `0x0A, 0x2C, 0x0A, 0x13, 0x77, 0x78, 0x69, 0x64, 0x5F, 0x79, 0x77, 0x67, 0x39, 0x74, 0x67, 0x64` 表中所有这个字段的第1、3个byte都是0A。
> 
> 我又看了一下UserNameList和displayName的字段，如果按UserNameList作为索引，displayName顺序是对的，只是会跳过没有设置昵称的成员。
> 
> 目前这个RoomData还没有看出门道。希望得到您的指点 感谢感谢。

protoc --decode_raw解析一下看看数据结构不就清楚了，0x0A这个字节是数据类型相关的

**Comment by RingoStudio** [comment]
感谢大佬，我这边终于拿到了群成员昵称。
从CharRoom表中取RoomData字段，建立一个proto格式，就可以解析出来了。
```
syntax = "proto3";
package XXXX.protobuf;
message ChatRoomData {
  message ChatRoomMember {
      string wxID = 1;
      string displayName = 2;
      int32 state = 3;
  }
  repeated ChatRoomMember members = 1;
  int32 field_2 = 2;
  int32 field_3 = 3;
  int32 field_4 = 4;
  int32 room_capacity = 5;
  int32 field_6 = 6;
  int64 field_7 = 7;
  int64 field_8 = 8;
}
```

这一切都是因为大佬的工作，变得特别简单。
再次表示感谢！

问题关闭。

**Comment by RingoStudio** [comment]
> 你这个是如何取到对应群的proto数据的 我还不知道 我都是全部挨个解析 - -

如果在一条SQL中同时查询STRING和BLOB字段会报错，因此分两次SELECT分别查询ID和RoomData，然后逐个解析，你可以参考我的c# SDK https://github.com/RingoStudio/ComWechatRobotCsharp/blob/master/sdk/WeChatSDK.cs
，有这个功能
