### ISSUE TITLE
关于AT群内成员时强制显示昵称的问题

### ISSUE THREAD

**Issue by RingoStudio** [ljc545w/ComWeChatRobot#27]
大佬，我又来打扰了。

在Issue #26 中，我解决了如何获取真实的群成员昵称。
但是由机器人发出的带有at的消息时会强制带有微信昵称。

尤其是进行多人AT的时候，我原本是想合并原有的单人AT，要AT不同的人做不同的事情，可是机器人在开头一股脑全都AT掉了。
目前我能做到的就是对文本进行如下的改进：
```
@Ringo Zhang @張 
----------
@机会 上游戏啦！
----------
@财神 该收菜啦！
```

我有以下几个建议，不知大佬可否采纳：
1. 自定义是否由机器人在消息开头增加AT；
2. 接口中提供一个昵称/wxid的字典，在发送时替换AT昵称。
3. 自定义AT在消息中的位置🤣

谢谢大佬。
希望机器人能越来越完美。

**Comment by ljc545w** [comment]
> 大佬，我又来打扰了。
> 
> 在Issue #26 中，我解决了如何获取真实的群成员昵称。 但是由机器人发出的带有at的消息时会强制带有微信昵称。
> 
> 尤其是进行多人AT的时候，我原本是想合并原有的单人AT，要AT不同的人做不同的事情，可是机器人在开头一股脑全都AT掉了。 目前我能做到的就是对文本进行如下的改进：
> 
> ```
> @Ringo Zhang @張 
> ----------
> @机会 上游戏啦！
> ----------
> @财神 该收菜啦！
> ```
> 
> 我有以下几个建议，不知大佬可否采纳：
> 
> 1. 自定义是否由机器人在消息开头增加AT；
> 2. 接口中提供一个昵称/wxid的字典，在发送时替换AT昵称。
> 3. 自定义AT在消息中的位置🤣
> 
> 谢谢大佬。 希望机器人能越来越完美。

这个不能算问题，本身自动加昵称就是为了方便。不过，倒是能多加一个是否自动添加昵称的BOOL参数，不影响原有使用

**Comment by ljc545w** [comment]
@RingoStudio 接口已更新

**Comment by RingoStudio** [comment]
> 这个不

太感谢了！
