### ISSUE TITLE
Docker支持

### ISSUE THREAD

**Issue by ChisBread** [ljc545w/ComWeChatRobot#28]
Hi, ljc545w
为了能够更方便地部署微信机器人, 我构建了一个在docker环境下注入win32 dll的镜像。
开源版本为[injector-box](https://github.com/ChisBread/injector-box)
并实现了docker版本的微信机器人服务端, 在我的私人项目[wechat-service](https://github.com/ChisBread/wechat-service)中给出了完整的文档和demo。设置为私有的部分原因是暂时没有完全开源的方案，且缺乏底层逆向技术支持，无法解决issue。
由于ComWeChatRobot维护积极，考虑到项目生命周期，我计划实现一个基于ComWeChatRobot的wechat-service
我能否邀请你参与wechat-service? 如果一切顺利的话，我们也许能给ComWeChatRobot添加更广泛的支持，并合并到ComWeChatRobot。

**Comment by ljc545w** [comment]
@ChisBread 你好，首先感谢邀请。我现在还有一些疑惑，暂时还不清楚需要做些什么，是需要为此项目添加websocket或http支持么？

**Comment by thelosttimes** [comment]
@ChisBread 你好，有3.7.0.26对应的镜像吗？

**Comment by ChisBread** [comment]
> 

不用做具体的事情，只是邀请

**Comment by ChisBread** [comment]
> @ChisBread 你好，有3.7.0.26对应的镜像吗？

是支持的，可以参考https://github.com/ChisBread/wechat-box 进行构建

**Comment by ChisBread** [comment]
https://github.com/ChisBread/wechat-service/invitations 邀请已发
这是我基于[wechat-bot](https://github.com/cixingguangming55555/wechat-bot)的实现，目前已经是较为可用的状态了。

**Comment by ljc545w** [comment]
> https://github.com/ChisBread/wechat-service/invitations 邀请已发 这是我基于[wechat-bot](https://github.com/cixingguangming55555/wechat-bot)的实现，目前已经是较为可用的状态了。

已收到。再次感谢

**Comment by ChisBread** [comment]
不用感谢～多亏了你的项目，wechat-service之后可以增加更多功能
issue先close了，希望我之后可以给ComWeChatRobot提PR :D
