### ISSUE TITLE
是否考虑新增新好友申请方法

### ISSUE THREAD

**Issue by Kerwin1202** [ljc545w/ComWeChatRobot#29]
我是因为一天不定时会收到好友同意请求，但是微信新好友时没有提醒的，等我看到都过了好久了

所以如果有接口可以接收到消息给自己提醒  或 有自动同意的就可以同意了

**Comment by ljc545w** [comment]
@Kerwin1202 接收消息配合同意好友申请接口就可以实现自动通过的

**Comment by Kerwin1202** [comment]
新版微信支持给某个人打标签，这种应该现在没有吧。加我的基本上都是一类人，所以我默认同意都会加标签。看方法貌似目前没有。

![image](https://user-images.githubusercontent.com/16319833/173388856-7201989d-c443-48ec-9538-0d63ff976810.png)
