### ISSUE TITLE
好友检测报错

### ISSUE THREAD

**Issue by ZdDroid** [ljc545w/ComWeChatRobot#3]
有些好友 Name 会有 JSON 的格式字符 比如 "
建议 C++ 层里使用 Json 库生成返回信息
或者 wxRobot.py 内 65 行后面加一行代码简单处理:
AddressBookString = AddressBookString.replace('""', '"\\"')
![image](https://user-images.githubusercontent.com/43038779/160290971-057c701f-68bf-44f0-985b-fedd082adc42.png)

**Comment by ljc545w** [comment]
> 
您好，感谢您的反馈和建议，我将尝试在C++中替换相关字符。

**Comment by ljc545w** [comment]
> 有些好友 Name 会有 JSON 的格式字符 比如 " 建议 C++ 层里使用 Json 库生成返回信息 或者 wxRobot.py 内 65 行后面加一行代码简单处理: AddressBookString = AddressBookString.replace('""', '"\"') ![image](https://user-images.githubusercontent.com/43038779/160290971-057c701f-68bf-44f0-985b-fedd082adc42.png)

已经在C++中添加了字符替换，将原始信息中的”替换为\"，研究COM接口返回类型比较耗时，所以暂时还是以字符串返回，再次感谢您的反馈，如果没有别的问题，我将在两天后关闭这个Issue

**Comment by ZdDroid** [comment]
可以使用 json 库序列化成 string 再返回,调用方再次反序列化 这样能避免维护处理 josn 字符关键字/Unicode字符/emoji 等.. 
推荐单文件 json 库 :
https://github.com/nlohmann/json API友好
https://github.com/dropbox/json11 C++11,使用方便

**Comment by ljc545w** [comment]
> 可以使用 json 库序列化成 string 再返回,调用方再次反序列化 这样能避免维护处理 josn 字符关键字/Unicode字符/emoji 等.. 推荐单文件 json 库 : https://github.com/nlohmann/json API友好 https://github.com/dropbox/json11 C++11,使用方便

感谢推荐，我已粗略浏览了这两个项目，有空的时候（大概周末）我会在此项目中应用。

**Comment by ljc545w** [comment]
已对通讯录列表做了新的处理，现在使用SAFEARRAY返回数据（一个三维数组），并不是您推荐的json库不好用，一来是想帮其他人省去一些配置环境的时间，其次我也想尝试下其他类型的返回。
