### ISSUE TITLE
请问，可以获取公众号文章么

### ISSUE THREAD

**Issue by yxj1028530975** [ljc545w/ComWeChatRobot#30]
没有看见相关接口，公众号文章采集的

**Comment by ljc545w** [comment]
> 

目前可以用接收消息，消息类型为49。或者数据库查询，PublicMsg.db，PublicMsg表中的CompressContent字段，需要自己写一个解压缩算法。

**Comment by yxj1028530975** [comment]
数据库查询的数据是本地数据库存储的数据么。除了这个PublicMsg

**Comment by ljc545w** [comment]
> 数据库查询的数据是本地数据库存储的数据么。除了这个PublicMsg

查询是实时的

**Comment by yxj1028530975** [comment]
数据库的这些表和字段，哪里可以 查看

**Comment by ljc545w** [comment]
> 数据库的这些表和字段，哪里可以 查看

GetDbHandles会返回数据库句柄，库名，以及库中所有表的建表语句。如果想看的更清楚，可以把数据库备份出来，用连接工具打开

**Comment by yxj1028530975** [comment]
ok，解决了

**Comment by yxj1028530975** [comment]
![image](https://user-images.githubusercontent.com/39391951/173785633-d3e4243b-3d37-4ef0-b886-90b346ad72c8.png)
![image](https://user-images.githubusercontent.com/39391951/173785673-18352068-b6c4-4299-abde-b2ba0aa3bdea.png)
数据结构，转换了很多编码都不行，你说的解压缩算法能提供下思路吗

**Comment by ljc545w** [comment]
@yxj1028530975 算法类似LZ77

**Comment by yxj1028530975** [comment]
太难了，搞不定，python的方式，等大大有空搞一搞

**Comment by yxj1028530975** [comment]
@Mmmmabury http地址可以获取，标题什么的话要再请求一遍文章获取，有点麻烦

**Comment by yxj1028530975** [comment]
如果没有解压缩，获取到的文章的url，只有一条。
我有一个问题，我发现今天获取的文章不是最新的，而是昨天发布的，不知道为什么会这样。

**Comment by ljc545w** [comment]
> 如果没有解压缩，获取到的文章的url，只有一条。 我有一个问题，我发现今天获取的文章不是最新的，而是昨天发布的，不知道为什么会这样。 我的sql f'SELECT * FROM "PublicMsg" where StrTalker="{wxid}" ORDER BY CreateTime DESC limit 1'

只有PC端收到的消息，或者最近同步的消息才会入库，如果想不漏就得一直挂着。

**Comment by ljc545w** [comment]
> 

一直都没有定位到查数据的地方，也不知道怎么触发

**Comment by iicey** [comment]
public Map<String, String> decode(String str) {
        if (str == null || !str.startsWith("~SEMI_XML~")) {
            return null;
        }
        String substring = str.substring(10);
        Map<String, String> hashMap = new HashMap<>();
        int length = substring.length() - 4;
        int i = 0;
        while (i < length) {
            int i2 = i + 1;
            try {
                int i3 = i2 + 1;
                int charAt = (substring.charAt(i) << 16) + substring.charAt(i2) + i3;
                String substring2 = substring.substring(i3, charAt);
                int i4 = charAt + 1;
                int i5 = i4 + 1;
                i = (substring.charAt(charAt) << 16) + substring.charAt(i4) + i5;
                hashMap.put(substring2, substring.substring(i5, i));
            } catch (Exception ignored) {
            }
        }
        return hashMap;
    }

**Comment by ljc545w** [comment]
> ```
> public Map<String, String> decode(String str) {
>     if (str == null || !str.startsWith("~SEMI_XML~")) {
>         return null;
>     }
>     String substring = str.substring(10);
>     Map<String, String> hashMap = new HashMap<>();
>     int length = substring.length() - 4;
>     int i = 0;
>     while (i < length) {
>         int i2 = i + 1;
>         try {
>             int i3 = i2 + 1;
>             int charAt = (substring.charAt(i) << 16) + substring.charAt(i2) + i3;
>             String substring2 = substring.substring(i3, charAt);
>             int i4 = charAt + 1;
>             int i5 = i4 + 1;
>             i = (substring.charAt(charAt) << 16) + substring.charAt(i4) + i5;
>             hashMap.put(substring2, substring.substring(i5, i));
>         } catch (Exception ignored) {
>         }
>     }
>     return hashMap;
> }
> ```

这段逻辑是解压xml的嘛？

**Comment by iicey** [comment]
> > ```
> > public Map<String, String> decode(String str) {
> >     if (str == null || !str.startsWith("~SEMI_XML~")) {
> >         return null;
> >     }
> >     String substring = str.substring(10);
> >     Map<String, String> hashMap = new HashMap<>();
> >     int length = substring.length() - 4;
> >     int i = 0;
> >     while (i < length) {
> >         int i2 = i + 1;
> >         try {
> >             int i3 = i2 + 1;
> >             int charAt = (substring.charAt(i) << 16) + substring.charAt(i2) + i3;
> >             String substring2 = substring.substring(i3, charAt);
> >             int i4 = charAt + 1;
> >             int i5 = i4 + 1;
> >             i = (substring.charAt(charAt) << 16) + substring.charAt(i4) + i5;
> >             hashMap.put(substring2, substring.substring(i5, i));
> >         } catch (Exception ignored) {
> >         }
> >     }
> >     return hashMap;
> > }
> > ```
> 
> 这段逻辑是解压xml的嘛？

是的，代码来自安卓微信的7.0.20

**Comment by yxj1028530975** [comment]
> > > ```
> > > public Map<String, String> decode(String str) {
> > >     if (str == null || !str.startsWith("~SEMI_XML~")) {
> > >         return null;
> > >     }
> > >     String substring = str.substring(10);
> > >     Map<String, String> hashMap = new HashMap<>();
> > >     int length = substring.length() - 4;
> > >     int i = 0;
> > >     while (i < length) {
> > >         int i2 = i + 1;
> > >         try {
> > >             int i3 = i2 + 1;
> > >             int charAt = (substring.charAt(i) << 16) + substring.charAt(i2) + i3;
> > >             String substring2 = substring.substring(i3, charAt);
> > >             int i4 = charAt + 1;
> > >             int i5 = i4 + 1;
> > >             i = (substring.charAt(charAt) << 16) + substring.charAt(i4) + i5;
> > >             hashMap.put(substring2, substring.substring(i5, i));
> > >         } catch (Exception ignored) {
> > >         }
> > >     }
> > >     return hashMap;
> > > }
> > > ```
> > 
> > 
> > 这段逻辑是解压xml的嘛？
> 
> 是的，代码来自安卓微信的7.0.20

解压成功了吗，可以改写成python的么

**Comment by iicey** [comment]
@yxj1028530975 目前只是提供解压代码，并没有做测试，原因如下：
微信电脑版3.6.0.18，启动python程序后微信会崩溃重启，不理解是为什么

**Comment by ljc545w** [comment]
现在增加了获取公众号历史消息功能，可以测试一下，注意每天量不要太大。
