### ISSUE TITLE
已经注册了COM 不能通过DLL直接加载函数吗

### ISSUE THREAD

**Issue by lovezm** [ljc545w/ComWeChatRobot#31]
![image](https://user-images.githubusercontent.com/10624938/173602002-69210fdc-a318-46e6-8c7d-2eaf5b699885.png)
想用易语言开发

**Comment by lovezm** [comment]
调用是知道了  不知道为什么发不出消息 - - 
![image](https://user-images.githubusercontent.com/10624938/173612719-9b15ed04-a5c3-494a-b63f-c164358dc360.png)
![image](https://user-images.githubusercontent.com/10624938/173612863-4c2da458-3c8c-4734-94d5-ea65088c30db.png)

**Comment by ljc545w** [comment]
@lovezm 开发32位程序是无需使用COM的，使用远程线程直接调用DLL导出函数就行。发送消息之前需要先调用CStartRobotService将DLL注入到微信，如果缺少这一步，大多数API都无效。

**Comment by lovezm** [comment]
DLL和COM里面的函数好像不太一样   COM里面的CReceiveMessage应该是监控消息吧 如何获取到呢

**Comment by ljc545w** [comment]
@lovezm Hook类的接口，一般都会有一个配套的启动接口，接收消息，需要先CStartReceiveMessage启动Hook，然后收到的消息才会保存到某个容器中，这时使用CReceiveMessage才会有效

**Comment by lovezm** [comment]
Thanks♪(･ω･)ﾉ 实现了 
![image](https://user-images.githubusercontent.com/10624938/173718200-529f599d-7c0a-46a6-be5f-6b9875c5b2a1.png)

**Comment by lovezm** [comment]
不过我发现监听久了  返回值是0  然后接收不到消息了  CStopRobotService卸载后 再start也是一样

**Comment by ljc545w** [comment]
@lovezm 放了多久出现的这个问题？

**Comment by lovezm** [comment]
2个小时左右 10钟出门的 挂着监听  延迟0.5秒一次  12.30收到最后一条消息。 而且有时候还会所有接口都不好使  不过CGetWeChatVer是正常的 COM卸载重新注册了也一样

**Comment by lovezm** [comment]
![1](https://user-images.githubusercontent.com/10624938/173739166-6286f9ff-3efd-41e7-b8b7-e1a0e4479839.gif)

**Comment by ljc545w** [comment]
> 

看起来像是hProcess失效了，之前没有考虑这个变量的周期，有空我看看是不是这个问题

**Comment by lovezm** [comment]
我去洗了个澡 回来 又正常了 可以给文件助手发送消息了。

**Comment by lovezm** [comment]
看来是有点问题

**Comment by ljc545w** [comment]
@lovezm 似乎是之前解决这个问题的代码被覆盖了，CloseHandle之后没有把hProcess设置为NULL，再次调用StartService就访问了无效句柄。我重新提交下

**Comment by ljc545w** [comment]
@lovezm 可以试下，现在启停服务两个接口应该正常了。但暂时还不清楚挂机时间久了会不会导致句柄失效，如果是的话就需要加一个刷新句柄接口了。

**Comment by lovezm** [comment]
我再测试一下  另外问一下CReceiveMessage是需要一直调用的吗 我现在是延迟0.5秒调用一次 高频调用不知道会不会造成封号  有没有收到消息主动推送的
“type” | “isSendMessage” | “time” | “from” | “wxid” | “message” | “filepath” | “1” | “0” | “2022-06-15 15:01:13” | “momodeshouhuwen” | “momodeshouhuwen” | “有事吗” | “”

**Comment by ljc545w** [comment]
> 我再测试一下 另外问一下CReceiveMessage是需要一直调用的吗 我现在是延迟0.5秒调用一次 高频调用不知道会不会造成封号 有没有收到消息主动推送的 “type” | “isSendMessage” | “time” | “from” | “wxid” | “message” | “filepath” | “1” | “0” | “2022-06-15 15:01:13” | “momodeshouhuwen” | “momodeshouhuwen” | “有事吗” | “”

这个问题我也思考过，通过COM的话，没有想到太好的办法，或许可以让注入的DLL也调用COM实现消息推送，这样也只是降低了对微信的负荷。可能websocket或http才是最终解决方案吧

**Comment by ljc545w** [comment]
> 我再测试一下 另外问一下CReceiveMessage是需要一直调用的吗 我现在是延迟0.5秒调用一次 高频调用不知道会不会造成封号 有没有收到消息主动推送的 “type” | “isSendMessage” | “time” | “from” | “wxid” | “message” | “filepath” | “1” | “0” | “2022-06-15 15:01:13” | “momodeshouhuwen” | “momodeshouhuwen” | “有事吗” | “”

这个问题我也思考过，通过COM的话，没有想到太好的办法，或许可以让注入的DLL也调用COM实现消息推送，这样也只是降低了对微信的负荷。可能websocket或http才是最终解决方案吧

**Comment by lovezm** [comment]
话说支持多开吗

**Comment by ljc545w** [comment]
@lovezm 给你逐个解答下
如果字段是sendto，而不是from，说明这是你发出的消息，所以跟wxid是一样的，收到的消息两者才会有区别。
目前不支持多开。
收到好友申请后，解析xml消息拿到v3和v4(ticket)这两个数据，然后调用CVerifyFriendApply。

**Comment by lovezm** [comment]
嗯 解析好友弄好了 监控到的消息能不能加上昵称或者群名啊
![image](https://user-images.githubusercontent.com/10624938/173789058-fadaa28d-0ce4-446e-a394-b2df80b5232e.png)

**Comment by lovezm** [comment]
CReceiveMessage似乎已经没问题了

**Comment by ljc545w** [comment]
可以的，这样能方便一点，顺便把接收到消息的其他扩展信息也补一补，差不多是该填坑了

**Comment by lovezm** [comment]
![image](https://user-images.githubusercontent.com/10624938/173793372-4878603a-11e2-40f0-93b1-cae8ec69740b.png)

**Comment by lovezm** [comment]
还有朋友圈也可以hook 我目前用的vlw框架的 可以参考一下 他还可以发朋友圈 估计是混用协议 pc上好像是没有发朋友圈的功能

**Comment by ljc545w** [comment]
CSendArticle的abstract，文章摘要，就是那个卡片标题下面显示的内容。
CSendCard的receiver，名片消息接收人，发给谁就写谁的wxid，sharedwxid就是被分享的人的wxid
CCheckFriendStatusFinish，这个接口写的确实不怎么明确，其实是取消好友状态码hook用的
CSearchContactByNet，网络查询用户信息，微信号手机号QQ号之类的，需要v3数据加好友的话就要先用这个查出来
CAddBrandContact，关注公众号的。
写注释和文档太难了，等试着优化完接收消息，把这块空白也补上

**Comment by ljc545w** [comment]
发朋友圈只能自己组包走协议，研究耗时而且更不安全，还是等官方功能吧，也怕时间投进去了但搞不定

**Comment by lovezm** [comment]
有关注公众号是不是也有取关公众号

**Comment by lovezm** [comment]
能获取公众号吗

**Comment by ljc545w** [comment]
暂时没有加取关公众号。获取公众号ID的话，可以先用搜狗微信。搜一搜相关的接口还没做呢

**Comment by lovezm** [comment]
对了你看能不能给startbot加上个禁止更新 我下午stop的时候微信崩溃了 然后自动升级了最新版。  我是关掉自动更新了的

**Comment by lovezm** [comment]
监听消息又又又出bug了 监听不到了 其他接口正常

**Comment by liulinlin** [comment]
> 对了你看能不能给startbot加上个禁止更新 我下午stop的时候微信崩溃了 然后自动升级了最新版。 我是关掉自动更新了的

我也碰到这个问题了，貌似现在是碰到安全漏洞的时候会自动更新。

**Comment by lovezm** [comment]
https://github.com/ldcsaa/HP-Socket  好东西~

**Comment by lovezm** [comment]
> > 对了你看能不能给startbot加上个禁止更新 我下午stop的时候微信崩溃了 然后自动升级了最新版。 我是关掉自动更新了的
> 
> 我也碰到这个问题了，貌似现在是碰到安全漏洞的时候会自动更新。

我今天又自动更新了

**Comment by ljc545w** [comment]
> > > 对了你看能不能给startbot加上个禁止更新 我下午stop的时候微信崩溃了 然后自动升级了最新版。 我是关掉自动更新了的
> > 
> > 
> > 我也碰到这个问题了，貌似现在是碰到安全漏洞的时候会自动更新。
> 
> 我今天又自动更新了

我也不知道怎么才能完全禁用，修改版本号搞不了启动的那次更新。改WeChatWin.dll和WeChat.exe几个字节可能比较彻底，但也有个外部更新程序。

**Comment by ljc545w** [comment]
> https://github.com/ldcsaa/HP-Socket 好东西~

接收消息逻辑优化了，现在用的连接点，是真正的回调，你试试用易实现sink

**Comment by lovezm** [comment]
还是老的实现方法 就是一直监听   
我刚试小程序消息 使用appid的话 发送不出去  是不是有别的参数 这个appid是从监听消息里面提取出来的
![image](https://user-images.githubusercontent.com/10624938/174085554-14d0683e-1792-4ac2-965c-eb9002911a15.png)

**Comment by ljc545w** [comment]
![1655388203819(1)](https://user-images.githubusercontent.com/67629154/174087613-c5b7187e-a783-41ee-9f5d-a4a767fa2b75.jpg)
这个username，我都没注意xml里面还有个appid标签

**Comment by lovezm** [comment]
嗯 这个对了 我还以为是appid = = 
![image](https://user-images.githubusercontent.com/10624938/174088329-c59117f9-ebe6-4b90-be3c-84494eaccdaa.png)

**Comment by lovezm** [comment]
大佬有群吗 拉一个交流啊 tg或者vx的都行

**Comment by lovezm** [comment]
我试试  接收消息挂了一晚上 没有出问题 不过还是需要加上发送者的昵称和群昵称 消息都不知道是谁发的  wxid每次还要CGetWxUserInfo一下 - -

**Comment by lovezm** [comment]
第一条消息群消息：2022-06-16 22:19:32
最后一条消息好友消息：2022-06-17 12:39:34

**Comment by lovezm** [comment]
这是目前消息监听持续时间

**Comment by lovezm** [comment]
> ```
> @echo off
> 
> md %USERPROFILE%\AppData\Roaming\Tencent\WeChat\patch
> echo %USERPROFILE%\AppData\Roaming\Tencent\WeChat  
> echo Y|cacls %USERPROFILE%\AppData\Roaming\Tencent\WeChat\patch /T /P %USERNAME%:N
> echo 设置完成
> pause
> ```
> 
> bat批处理文件，修改VX的文件夹的权限，可以防止更新，试试？ 另外我最近也关注到了这个项目，如果有群的话请务必带上我，谢谢

会不会对文件接收造成影响

**Comment by ljc545w** [comment]
@lovezm 最近在尝试用websocket，64位程序注入DLL到32位已经搞定了，可能不久就能有一套新接口。
