### ISSUE TITLE
请教下如何获取图片等文件的绝对路径？

### ISSUE THREAD

**Issue by shangdev** [ljc545w/ComWeChatRobot#33]
接收消息中可以获取到文件、图片的相对路径，如 xx\FileStorage\Image\2022-06\827295d15ae74d65267c4899a31147dd.dat

但是绝对路径却没有显示，如：E:\WeChat Files\xx

看到其他人的处理方式是，获取AccInfo.dat文件路径的偏移，然后字符串截取获取绝对路径前缀。

但是我用CE挂载微信后查不到这个偏移，请问还有其他方式能获取到这个路径吗？

**Comment by ljc545w** [comment]
> 接收消息中可以获取到文件、图片的相对路径，如 xx\FileStorage\Image\2022-06\827295d15ae74d65267c4899a31147dd.dat
> 
> 但是绝对路径却没有显示，如：E:\WeChat Files\xx
> 
> 看到其他人的处理方式是，获取AccInfo.dat文件路径的偏移，然后字符串截取获取绝对路径前缀。
> 
> 但是我用CE挂载微信后查不到这个偏移，请问还有其他方式能获取到这个路径吗？

直接搜AccInfo.dat的地址肯定没有啊，浏览内存区域，找到前面的盘符再搜。
WeChatWin.dll+2363068，这是3.7.0.26的偏移
