### ISSUE TITLE
请问如何使用呢？

### ISSUE THREAD

**Issue by um-why** [ljc545w/ComWeChatRobot#34]
我按照以下步骤：
1、安装全新的wechat 3.7.0.26；
2、注册COM  CWeChatRobot.exe /regserver ;
3、安装python 的扩展依赖；
4、启动Python 目录中的 test.py ；报错如图片

请问应该如何使用？
![微信截图_20220617184150](https://user-images.githubusercontent.com/24377892/174283546-17f245bb-9bca-4601-a962-93cff8e91027.png)

**Comment by um-why** [comment]
重新微信，再次注册COM也不行

**Comment by ljc545w** [comment]
> 重启微信，再次注册COM也不行
> 
> 我的系统环境是 win 10 64位； python 3.9.2
> 
> 安装的python 扩展就是demo里面的 comtypes==1.1.11 和 psutil==5.9.0

请确认以管理员执行`CWeChatRobot.exe /regserver`

**Comment by Irvingouj** [comment]
同样无法启动，已确认以管理员执行CWeChatRobot.exe /regserver
![微信bot python](https://user-images.githubusercontent.com/49964599/174499957-f9d0a1a9-4e96-4dcb-bfc4-df3eeb25a47e.PNG)

**Comment by um-why** [comment]
> 

已经可以了，谢谢。

**Comment by um-why** [comment]
> 同样无法启动，已确认以管理员执行CWeChatRobot.exe /regserver ![微信bot python](https://user-images.githubusercontent.com/49964599/174499957-f9d0a1a9-4e96-4dcb-bfc4-df3eeb25a47e.PNG)

你试试别用power shell ，换用命令提示符，试试

**Comment by Irvingouj** [comment]
我依然有同样问题，请问方便私下联系一下吗？可以付费换取技术支持。

**Comment by ljc545w** [comment]
> 我依然有同样问题，请问方便私下联系一下吗？可以付费换取技术支持。

你的问题是版本号不对，COM中实现的接口都已经打出来了，你的微信版本号是3.7.0.30，换成3.7.0.26就可以了。版本不对会崩溃的

**Comment by Irvingouj** [comment]
谢谢，请问特定版本的微信哪里可以下载到呢

**Comment by ljc545w** [comment]
> 谢谢，请问特定版本的微信哪里可以下载到呢

https://aichunjing.lanzoui.com/b00dd197e

这是别人整理的链接，看起来又更新3.7.1了
