### ISSUE TITLE
使用python运行时微信会崩溃怎么解决

### ISSUE THREAD

**Issue by Jackyfi** [ljc545w/ComWeChatRobot#35]
求大佬指教
![image](https://user-images.githubusercontent.com/77333092/174346139-516d3f96-a373-4e5e-adf7-1213b349cac6.png)
![image](https://user-images.githubusercontent.com/77333092/174346374-94f172ba-e08c-4eea-a8ac-ab148f802b54.png)
用的时测试的那个代码

**Comment by lovezm** [comment]
我猜是调用了stopbotserver导致的 我也会

**Comment by ljc545w** [comment]
最新提交已经解决此问题，之前给发文章接口加图片参数的时候，打印图片路径没有判断是否空指针

**Comment by Jackyfi** [comment]
> 最新提交已经解决此问题，之前给发文章接口加图片参数的时候，打印图片路径没有判断是否空指针
下载了最新的，好像还是会报这个错误，然后崩溃

**Comment by Jackyfi** [comment]
> 我猜是调用了stopbotserver导致的 我也会

这个怎么解决的

**Comment by ljc545w** [comment]
@Jackyfi 请确定微信版本是3.7.0.26，如果是，麻烦在交互环境中执行测试代码，以便更准确的定位无效或报错接口

**Comment by QiGuaiDeDiDi** [comment]
我看了你的代码，是获取不到info，导致在将info进行dict化时出错。
基本上这个问题是因为微信版本问题，微信会自动更新，可以重新安装对应版本微信。

**Comment by yxj1028530975** [comment]
微信重启就会自动更新，设置了也没用，之前我也遇到了。

**Comment by QiGuaiDeDiDi** [comment]
> 

设置也没用，3.7.0.26版本的微信，会强制更新某些版本。
去改host文件可以解决这个问题

**Comment by Jackyfi** [comment]
谢谢大佬们，原来是微信自动更新了，重新下载就可以了
