### ISSUE TITLE
更新了socket监听啊 端口是多少啊 

### ISSUE THREAD

**Issue by lovezm** [ljc545w/ComWeChatRobot#41]
那个太多了 很难翻 重新开一个

**Comment by lovezm** [comment]
嗯 比一直请求好多了

**Comment by lovezm** [comment]
话说我创建了 返回1 但是连接还是断开啊 是用的tcp还是ws

**Comment by lovezm** [comment]
试了一下tcp连接也是秒断  监听返回1是启动成功了吗

**Comment by ljc545w** [comment]
> 试了一下tcp连接也是秒断 监听返回1是启动成功了吗

1是失败的。而且应该建立一个server，C++里面写的逻辑是向服务器提交数据。

**Comment by RingoStudio** [comment]
我想来分享一下，我用c#写的那个sdk，从两周前偶然碰到大佬的这个项目开始，到今天已经运行了有一周，这期间我用ComWechatRobot直接代替了我原有的使用ws的bot底层。

在过去的十天时间里，我的bot同时运行了两个实例，分别跑在我自己的电脑上和一台腾讯云轻量app服务器上，其中最多的一个实例同时应对一千五百人的交互，因为曾经的一些经验，我做了带有时间间隔的消息发送队列，以最大程度保持稳定（在我发出来的c# 版sdk中含有此功能）。
两个实例大部分时间顺畅运行，从无wx报错和闪退。但是平均两天会发生电脑死机蓝屏，因为最近比较忙，还没有调查造成此问题的原因。但是我为bot增加了每天自动重启的设定，死机的问题得到缓解。

作为一名业余选手，我感激大佬的工作以及在曾经的issue中对我的帮助，另外更高兴的是大佬的项目表现如此优异。
由于GH没有评论区，在此插楼特别表示感谢！

**Comment by ljc545w** [comment]
@RingoStudio 也感谢你的C# SDK

**Comment by lovezm** [comment]
新的监听方式我还没有实现 - - 现在返回0 也是无法连接  我只用了COM版的DLL  是不是还需要注入socket里的DLL啊

**Comment by ljc545w** [comment]
@lovezm 不用啊，socket里的是为以后开发http接口留的一个配置。你可以参考下python的写法，SDK要实现的是socket server，不是client；收到消息后，DLL里的处理程序会主动连接你指定的端口，并把数据传输过来，传完就自动断开等下一条消息。

**Comment by lovezm** [comment]
![image](https://user-images.githubusercontent.com/10624938/175757937-e9f3e9b4-1a9a-4a13-9946-639e7ee25309.png)
误解了 - -一直以为是创建server 原来是连接server来推送消息

**Comment by lovezm** [comment]
易语言的实现好蛋疼 需要援助
![image](https://user-images.githubusercontent.com/10624938/175761704-bbd0b1ac-1ae3-4846-89a9-77eafc986729.png)
wintypes.DWORD算是4个字节集
comtypes.c_wchar是几个啊？

**Comment by lovezm** [comment]
tcp返回的固定数据长度是132004

**Comment by lovezm** [comment]
用nodejs看了看是三个buffer数据 分别是什么啊（太菜了 ）
65536
65536
932

**Comment by ljc545w** [comment]
c_wchar就是宽字符，C中的wchar_t，占两个字节，132004长度的数据是一个结构体。类型如下：
struct ScoketMsgStruct {
	int messagetype;
	BOOL isSendMessage;
	wchar_t sender[80];
	wchar_t wxid[80];
	wchar_t message[0x1000B];
	wchar_t filepath[MAX_PATH];
	wchar_t time[30];
};
成员长度字节数分别是4、4、80*2、80*2、0x1000B*2、260*2、30*2

**Comment by lovezm** [comment]
E取出来数据只有第一个字符串 我吐了  我得去研究研究

**Comment by lovezm** [comment]
socket监听返回的是buffer数据 也是一个结构体吗

**Comment by ljc545w** [comment]
server返回给C++的？随便什么都可以，只要有返回就行，收到返回数据后线程会正常结束。
如果不好构造结构体，就转成byte数组直接取相应的长度也可以的

**Comment by lovezm** [comment]
应该没有body之类的吧  直接返回的就是监听消息

**Comment by ljc545w** [comment]
> 应该没有body之类的吧 直接返回的就是监听消息

没有body，整块数据就是消息结构体，结构体的size就是132004

**Comment by lovezm** [comment]
![image](https://user-images.githubusercontent.com/10624938/175766820-4da9bee2-58a4-42b0-9643-db4a49761c36.png)
jie解析出来了 不过如果是自己在群里发送的 还是只显示群id么 不显示自己id

**Comment by lovezm** [comment]
不过好像作用不大 通过isSendMessage就可以判断了 = =

**Comment by ljc545w** [comment]
发送的跟接收，结构体是同一个，但逻辑不一样的

**Comment by lovezm** [comment]
有一个奇怪的bug  就是在监听消息解析到的wxid调用com获取wxinfo是失败的 但是手动查询wxid是可以的 是不是在线程里面不能调用或者是其他的原因

**Comment by ljc545w** [comment]
> 

这算是COM的特性了，整理的接口只能供一个线程使用，在另外一个线程里，需要额外调用CoInitalize
然后还需要在线程中重新CreateObject，得到的接口才能供线程使用
但是不需要再次调用StartRobotService，只需要重新整理接口

**Comment by lovezm** [comment]
原来如此 解决了

**Comment by lovezm** [comment]
1文本消息 43视频消息 47图片表情 49小程序消息  10000系统消息 还有啥消息

**Comment by hibmm** [comment]
> 1文本消息 43视频消息 47图片表情 49小程序消息 10000系统消息 还有啥消息

图片=3，其他（文件、小程序、转账、XML链接等）=49

**Comment by lovezm** [comment]
发现新问题  获取信息 群里面的wxid获取的 没有群内昵称 只有他本身的昵称

**Comment by lovezm** [comment]
![image](https://user-images.githubusercontent.com/10624938/176677321-d9866549-e39d-498a-810e-3a6f7df7ccda.png)
群里基本都有群内昵称 获取不到就很麻烦 不好统计业主信息啊哈哈

**Comment by ljc545w** [comment]
参考下#26 解析pb

**Comment by lovezm** [comment]
就比如select NickName from Contact where UserName="xxx"
有没有可以对应群id取出的sql语句

**Comment by ljc545w** [comment]
> 就比如select NickName from Contact where UserName="xxx" 有没有可以对应群id取出的sql语句

有的，获取数据库句柄接口，一并返回的还有库中各个表的建表语句。
或者`select * from xxx limit 1`，看看字段对应什么内容。比如这个表里面群ID是`ChatRoomName`

**Comment by lovezm** [comment]
![image](https://user-images.githubusercontent.com/10624938/176720320-1cde4175-d1f6-4d82-a6ad-bd1317d4f3c7.png)
没啥问题了 就是取句柄的方式有点傻  获取数据库 全部转成数值 过滤掉那些无法转换的 取第一个转换成功的用作句柄- -  返回的数据太多了 不知道怎样解析
有没有更好的方法
![image](https://user-images.githubusercontent.com/10624938/176720998-4a57adcc-5256-4b7c-8ee3-dfed4dfa2d97.png)

**Comment by ljc545w** [comment]
获取句柄返回的是一个三维的安全数组，得一层一层的遍历，把数据整理成想要的结构。
数据库查询用的都是原生的sqlite3 API，如果封号肯定不是因为这个。
现在没有朋友圈的库句柄。

**Comment by lovezm** [comment]
发送的消息过长似乎会导致崩溃

**Comment by kingking888** [comment]
python 跑test.py 出现以下提示是没有hook成功吗？

warning: Hook not success
