### ISSUE TITLE
问下大佬,微信群里接受的红包能够获取到发送者和红包的金额吗

### ISSUE THREAD

**Issue by September999999999** [ljc545w/ComWeChatRobot#44]
`{'type': 10000, 'sender': '18794550263@chatroom', 'wxid': '18794550263@chatroom', 'message': '发出红包，请在手机上查看', 'filepath': ''}
`
这个是目前接受的红包格式

**Comment by hibmm** [comment]
我觉得你的想法有点刑

**Comment by September999999999** [comment]
> 我觉得你的想法有点刑

Emmmm,想歪了,用途实际上是统计下昨日未运动打卡人群是否发红包

**Comment by hibmm** [comment]
> 

我以为你是想透视红包金额呢……那没事了

**Comment by ljc545w** [comment]
这个还没注意过，转账见别人弄过。红包的话一般是提示“请在手机上查看”，晚点我去内存看看再回复你。

**Comment by September999999999** [comment]
好的好的,谢谢

**Comment by ljc545w** [comment]
内存里也只有"收到红包，请在手机上查看"。附加的xml里也没有金额相关的
