### ISSUE TITLE
问题来了

### ISSUE THREAD

**Issue by hankssr** [ljc545w/ComWeChatRobot#46]
AttributeError: module 'comtypes.gen.WeChatRobotCOMLib' has no attribute 'IRobotEvent'

刚下载的大佬的更新,重新卸载,注册,然后运行就提示这个信息,求解?:)

**Comment by lovezm** [comment]
pip install comtypes==1.1.10

**Comment by ljc545w** [comment]
找到site-pakeages，把comtypes.gen目录缓存清了再运行

**Comment by hankssr** [comment]
> 找到site-pakeages，把comtypes.gen目录缓存清了再运行

搞定!
