### ISSUE TITLE
可否在后续版本中新增一下获取个人信息中的性别和微信登录状态的标识呢

### ISSUE THREAD

**Issue by I-am-not-a-dalao** [ljc545w/ComWeChatRobot#49]
3.6.0.18的性别偏移是0x222ECB8，0未知，1男，2女，
检查登录状态这里我不清楚该怎么去找了，好像也是个0、1状态标识
这里有一个[3.6.0.18](https://github.com/Greatfar/WeChatHelper/blob/b693a3d6b3a5e20be71cbaf8c0b204f0cce3c997/WeChatTools/InitWeChat.cpp#L66)的参照

**Comment by ljc545w** [comment]
登录标志之前看过了，有空加上吧

**Comment by ljc545w** [comment]
master分支已经加了这两个逻辑。

**Comment by I-am-not-a-dalao** [comment]
谢谢大佬[good]
