### ISSUE TITLE
Dll中调用SendArticle时微信奔溃了

### ISSUE THREAD

**Issue by shangdev** [ljc545w/ComWeChatRobot#5]
调用代码如下：
```
wchar_t title[0x100] = { 0 };
wchar_t description[0x100] = { 0 };
wchar_t url[0x100] = { 0 };
swprintf_s(title, L"天气预报");
swprintf_s(description, L"点击查看");
swprintf_s(url, L"htp://www.baidu.com");
SendArticle(wxid, title, description, url);
```

请教是什么原因、调用的方法不对吗、

**Comment by ljc545w** [comment]
参数直接用wchar_t*变量就可以了，用swprintf格式化，你得打印变量看看，是不是有问题

**Comment by shangdev** [comment]
对c不是很熟悉，是这样初始化变量吗：
```
wchar_t* title = (wchar_t*)L"天气预报";
wchar_t* description = (wchar_t*)L"点击查看";
wchar_t* url = (wchar_t*)L"htp://www.baidu.com";
```
不过经测试还是奔溃了，

**Comment by ljc545w** [comment]
> 对c不是很熟悉，是这样初始化变量吗：
> 
> ```
> wchar_t* title = (wchar_t*)L"天气预报";
> wchar_t* description = (wchar_t*)L"点击查看";
> wchar_t* url = (wchar_t*)L"htp://www.baidu.com";
> ```
> 
> 不过经测试还是奔溃了，

你好，写法是对的，虽然url有问题，但也不至于发不出去，我排查后再给你回应，最近事情比较多，可能会晚一点。

**Comment by ljc545w** [comment]
> 对c不是很熟悉，是这样初始化变量吗：
> 
> ```
> wchar_t* title = (wchar_t*)L"天气预报";
> wchar_t* description = (wchar_t*)L"点击查看";
> wchar_t* url = (wchar_t*)L"htp://www.baidu.com";
> ```
> 
> 不过经测试还是奔溃了，

你的wxid，是不是非wxid_开头的那种，目前获取个人信息的代码，没有兼容老的wxid，访问的时候把数据当成指针，就引发崩溃了。

**Comment by shangdev** [comment]
@ljc545w 是的，非wxid_开头。我改一下试试

**Comment by shangdev** [comment]
@ljc545w 

机器人ID获取方式修改一下就可以兼容了：

```
wchar_t* wselfwxid = UTF8ToUnicode((const char*)(WeChatWinBase + 0x222EB3C));
```

**Comment by ljc545w** [comment]
> 

老的wxid，偏移0x222EB3C处是数据，新的wxid，偏移0x222EB3C处是一个指针。后面我会加兼容的。

**Comment by ljc545w** [comment]
> @ljc545w
> 
> 机器人ID获取方式修改一下就可以兼容了：
> 
> ```
> wchar_t* wselfwxid = UTF8ToUnicode((const char*)(WeChatWinBase + 0x222EB3C));
> ```

已在工程中添加兼容老wxid；艾特消息后续会加接口，最近加班严重，只能抽空做。

**Comment by ljc545w** [comment]
> @ljc545w
> 
> 机器人ID获取方式修改一下就可以兼容了：
> 
> ```
> wchar_t* wselfwxid = UTF8ToUnicode((const char*)(WeChatWinBase + 0x222EB3C));
> ```

已在工程中添加兼容老wxid；艾特消息后续会加接口，最近加班严重，只能抽空做。
