### ISSUE TITLE
有群吗

### ISSUE THREAD

**Issue by oooooos** [ljc545w/ComWeChatRobot#52]
尊敬的开源作者你好，感谢您的开源代码对我帮助很大，请问有交流群吗

**Comment by ljc545w** [comment]
没有群；之前有考虑用ws或者http实现新的调用，做了注入，具体实现还没来得及弄，暂时还是使用COM吧。

**Comment by oooooos** [comment]
感谢回复 ，期待ws或http调用方式！

**Comment by izuanqian** [comment]
我建个q群，交流一下：735 321 479
