### ISSUE TITLE
python 跑test.py 出现以下提示该怎么办

### ISSUE THREAD

**Issue by kingking888** [ljc545w/ComWeChatRobot#56]
python 跑test.py 出现以下提示是没有hook成功吗？

warning: Hook not success

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by ljc545w** [comment]
确认注入成功再调用别的接口，StartService接口返回0代表成功。

**Comment by kingking888** [comment]
> 确认注入成功再调用别的接口，StartService接口返回0代表成功。

谢谢大佬百忙之中抽时间回复我，可能是本地ip已经被占用导致了起不来websocket服务，我把本地一些服务关掉重新开就可以了
