### ISSUE TITLE
关于图片自动下载的功能

### ISSUE THREAD

**Issue by tmsdy** [ljc545w/ComWeChatRobot#58]
![Snipaste_2022-07-18_14-28-54](https://user-images.githubusercontent.com/12005139/179455692-f84dd0c1-d492-4264-92ad-f7955319ed95.png)

修改了时间为 00:00-23:59，然后编译了重新注册了，自动下载还是不成功，必须手动点开图片，才会下载。 
是不是还有哪里需要设置？呢

**Comment by ljc545w** [comment]
这个地方之前写错了，那个时间是不自动下载的时间段，所以应该设置为"00:00-00:00"
git上我已经改正过

**Comment by duo** [comment]
设置成 "00:00-00:00" 有时候还是不会自动下载图片，不知道是为啥，所以我把 0x48D56B 也给 NOP 了

**Comment by ljc545w** [comment]
> 

请问有记录不下载的具体时段吗

**Comment by duo** [comment]
具体时间点不记得了，印象里中午，下午的时间点都有出现过不自动下载

**Comment by ljc545w** [comment]
> 具体时间点不记得了，印象里中午，下午的时间点都有出现过不自动下载

好的，那麻烦再看看加nop后还有没有问题，如果没问题的话，我就把nop也加进去。感谢

**Comment by duo** [comment]
![image](https://user-images.githubusercontent.com/18750/182493165-56004669-fc15-454b-9ebc-db1c4e133cfa.png)

我看这边是排除 00:30-07:30，当时我是中午下午都有出现过没自动下载，在微信里看图片都是有等待下载的按钮
在想是不是孤例，毕竟好像也有没看到别人反馈过这个问题
所以只能比较粗暴的把 0x48D56B 给 NOP , 目前图片的自动下载都一直正常了

**Comment by FengLiWeng** [comment]
那个自动保存图片的文件名称 和 聊天消息里面的 xml 信息好像对不上了.. 想知道自动保存的图片是谁发出来的,有什么办法吗?

**Comment by ljc545w** [comment]
> 

接收到图片或者文件消息时，会有个附加的filepath，从这个字段截取文件名再比对。后面会将保存文件名修改为消息的ID。
