### ISSUE TITLE
建议增加一个项目的格式化配置文件

### ISSUE THREAD

**Issue by amchii** [ljc545w/ComWeChatRobot#60]
他人fork之后可能只是修改了很小的一部分代码却因为格式化工具的差异导致git history大幅变动影响review，我查了一下好像clang-format可以通过在工作目录添加一个配置文件来定义代码风格，比如tab使用空格，int *x等等👀

**Comment by ljc545w** [comment]
有时间我看一下

**Comment by amchii** [comment]
我加了个git pre-commit hook搭配clang-format(Microsoft风格)可以在提交代码的时候自动检查和格式化。有兴趣可以看看。https://github.com/ljc545w/ComWeChatRobot/compare/master...amchii:ComWeChatRobot:feat/clang-format-with-pre-commit?expand=1

**Comment by ljc545w** [comment]
好的，下次提交时会添加格式化文件，之前都快忘了这件事。再次感谢

**Comment by amchii** [comment]
不客气的主要是我在用该项目开发我之前说的一个上层的工具(cli，rpc)，也应该给项目做贡献。
你可以看看我贴的[这个链接](https://github.com/ljc545w/ComWeChatRobot/compare/master...amchii:ComWeChatRobot:feat/clang-format-with-pre-commit?expand=1)格式前后对比，`.clang-format`里用的是VS Code的C++风格。`.pre-commit-config.yaml`已经配好了hook，只要`pip install pre-commit`(全局的pip，保证在环境变量PATH中），然后到需要hook的项目下执行`pre-commit install`，初始化后每次git commit就会自动格式化变动的文件了。
