### ISSUE TITLE
com接口支持远程调用吗

### ISSUE THREAD

**Issue by oooooos** [ljc545w/ComWeChatRobot#74]
对com接口不了解 请问com接口支持远程调用吗

**Comment by ljc545w** [comment]
我不知道你说的远程，是指何种。com和语言、平台无关，但一般是在Windows上使用。
注册过的COM组件，支持同一计算机上的其他编程语言，比如vbs，python，c#等调用。
跨计算机调用，还没有研究过。

**Comment by hibmm** [comment]
不太理解你说的这个远程调用，如果是远程线程的话，建议直接去调用DLL，作者全都写了导出函数，可以远程线程直接调用；
如果是网络调用的话，可能你得再封装一层
