### ISSUE TITLE
微信自动升级了，有历史版本下载地址吗大佬

### ISSUE THREAD

**Issue by ly1102** [ljc545w/ComWeChatRobot#75]
我电脑重启后，微信自动升级了。大佬们有历史版本下载地址吗？我搜了百度全是下载站，都是最新的3.7.5版本了。

**Comment by ljc545w** [comment]
链接：https://pan.baidu.com/s/1NeIoNN42ju_1saQvXMgFkA 
提取码：hspl
仅供参考
