### ISSUE TITLE
C#大佬大佬，可以根据好友信息（昵称，微信名）快速获取wxid吗？在线等

### ISSUE THREAD

**Issue by XiuiManeia** [ljc545w/ComWeChatRobot#78]
通过窗口拿到好友的备注名或者微信名，但不知道wxid。如果先GetFriends放进datagridview，再去里面搜索的话效率好低，5000个好友，就要在10000个格子里遍历查询，几秒就要查询一次，这样太低效了，不知道有没有接口可以直接实现？求大佬指点一下

**Comment by ljc545w** [comment]
快的话就用数据库吧，MicroMsg.db，Contact表，`select UserName as `wxid` from Contact where Nickname="xxx" or Alias="xxx"`,Alias就是微信号。字段大小写我可能没写对，获取到建表语句对着改一下。

**Comment by XiuiManeia** [comment]
> 快的话就用数据库吧，MicroMsg.db，Contact表，`` select UserName as `wxid` from Contact where Nickname="xxx" or Alias="xxx" ``,Alias就是微信号。字段大小写我可能没写对，获取到建表语句对着改一下。

大哥，这库在哪啊

**Comment by FengLiWeng** [comment]
https://github.com/RingoStudio/ComWechatRobotCsharp
参照这个版本的 demo 获取

**Comment by XiuiManeia** [comment]
> https://github.com/RingoStudio/ComWechatRobotCsharp 参照这个版本的 demo 获取

对不起，我看了很久但是以我的水平看不懂😢

**Comment by XiuiManeia** [comment]
> https://github.com/RingoStudio/ComWechatRobotCsharp 参照这个版本的 demo 获取

噢我懂了
