### ISSUE TITLE
检测好友状态只能检测491人

### ISSUE THREAD

**Issue by hkzxc1991** [ljc545w/ComWeChatRobot#79]
测试了两次，检测好友状态时，检测完第491个人就会报错，报错代码  friend_list = instance.GetFriendList()
![image](https://user-images.githubusercontent.com/29220990/184543471-10a10921-a7b2-4856-bb47-e5e700606afa.png)

**Comment by ljc545w** [comment]
信息太少，无法确定问题。可以把第491个好友单独拿出来检测下。

**Comment by hkzxc1991** [comment]
抱歉，应该是另外一个问题：获取好友数不全，实际是800+好友，只获取到491，另外一个微信号是3000+人，只获取到2700左右，这是什么问题造成的？
![image](https://user-images.githubusercontent.com/29220990/184899381-f5dbe817-5f7c-47ae-8d47-b0722d7f970c.png)

**Comment by ljc545w** [comment]
暂时不清楚原因，是会少一些，但少一半的情况还没有遇到过。

**Comment by SupernovaCooper** [comment]
可能是GetFriendList的问题，看demo中判断好友貌似 if 'wxid_' == item['wxid'][0:5]: 则认为是好友，实际上 有些好友的wxid并不是 wxid_开头。

**Comment by lucky1945** [comment]
能否检测删除状态

**Comment by ljc545w** [comment]
> 能否检测删除状态

对方删除你是可以的; 你删除对方，要看内存里还有没有TA
