### ISSUE TITLE
GetDbHandles 疑问,反馈小BUG

### ISSUE THREAD

**Issue by ZdDroid** [ljc545w/ComWeChatRobot#8]
尝试备份微信聊天记录(PublicMsg.db)发现 GetDbHandles 返回中并没有需要的库名
![image](https://user-images.githubusercontent.com/43038779/164191450-2955b01b-fc98-4270-a809-e59443aab8b0.png)
还有别的方式能读到到 PublicMsg.db 这个库吗
另外反馈小BUG: 
requirements.txt 中忘了添加依赖 psutil ,假如 python 没有安装这个库则会导致 Server 卡住,无法再次 StartService 必须重启微信

**Comment by ljc545w** [comment]
> 尝试备份微信聊天记录(PublicMsg.db)发现 GetDbHandles 返回中并没有需要的库名 ![image](https://user-images.githubusercontent.com/43038779/164191450-2955b01b-fc98-4270-a809-e59443aab8b0.png) 还有别的方式能读到到 PublicMsg.db 这个库吗 另外反馈小BUG: requirements.txt 中忘了添加依赖 psutil ,假如 python 没有安装这个库则会导致 Server 卡住,无法再次 StartService 必须重启微信

我一直以为psutil是python的标准库来着。。就没写进去。
那个地方保存了25张表，去重后确实只有这六个库，返回的没有问题；
如果要找更多的句柄，需要Hook一个函数，这个函数是sqlite3_open中的调用的openDataBase。

**Comment by ZdDroid** [comment]
了解,不过并不懂逆向 大佬有空再加上吧 十分感谢

**Comment by ljc545w** [comment]
有时间我会找一下，或者加一个离线解密的功能吧

**Comment by ljc545w** [comment]
目前已经能获取到PublicMsg.db的句柄
