### ISSUE TITLE
大哥大哥最后一问，sql语句上有个小小问题想请教一下，我太笨了百度了好久都不行

### ISSUE THREAD

**Issue by XiuiManeia** [ljc545w/ComWeChatRobot#80]
![image](https://user-images.githubusercontent.com/49738599/184635129-b5f12ceb-56a2-42cb-98fd-b1ea3cae76c5.png)

string Name = "QQ离线消息";
string sql = ($"SELECT * FROM Contact WHERE NickName = '{Name}'");
string sql = ("SELECT * FROM Contact WHERE NickName = '" + Name+"'");
string sql = (@"SELECT * FROM Contact WHERE NickName = """ + Name+@"""");

试了好多。 string sql = ("SELECT * FROM Contact WHERE Type = 3"); 数字就没问题

**Comment by XiuiManeia** [comment]
![image](https://user-images.githubusercontent.com/49738599/184636697-340f9ef9-394a-498c-9084-042233d2354a.png)
同样的语句，APPSO 英文就没问题

**Comment by XiuiManeia** [comment]
string Name = "QQ离线消息";
byte[] utf8Bytes = Encoding.Default.GetBytes(Name);
byte[] utf8bytes2 = Encoding.Convert(Encoding.Default, Encoding.UTF8,utf8Bytes);
Name = Encoding.Default.GetString(utf8bytes2);

编码问题，需要转换一下，百度抄的。。

**Comment by ljc545w** [comment]
你应该不需要处理字符编码的，COM接口要求的就是unicode编码，在执行sql前会转换为utf8。

**Comment by ljc545w** [comment]
这是个bug，等明天修正。

**Comment by XiuiManeia** [comment]
> 

大哥大哥等你的好消息，我就差这最后一步了👍


sql = $"SELECT UserName FROM Contact WHERE NickName = LIKE'{Name}%' or Remark = LIKE'{Name}'";
就差这一句，整个小工具就可以完整跑起来了

**Comment by ljc545w** [comment]
改好了，试一下吧。

**Comment by XiuiManeia** [comment]
> 改好了，试一下吧。

额大佬。。我之前都是直接引用您demo里的Interop.WeChatRobotCOMLib.dll，我挨个生成出来咋没这个呢
![image](https://user-images.githubusercontent.com/49738599/184856838-1d91e7dd-32d2-4d55-ad59-a4e2488afb62.png)

**Comment by ljc545w** [comment]
一直都没有那个东西的

**Comment by XiuiManeia** [comment]
> 一直都没有那个东西的
啊这惊了..那我该怎么引用到我的winform项目里呢。。之前一直都是引用的WeChatRobotCOMLib.dll

**Comment by ljc545w** [comment]
我也不知道你是怎么引用的。Release文件并不包含WeChatRobotCOMLib.dll。
COM代理在CWeChatRobot.exe中，接口具体实现在DWeChatRobot.dll中。

**Comment by XiuiManeia** [comment]
> 我也不知道你是怎么引用的。Release文件并不包含WeChatRobotCOMLib.dll。 COM代理在CWeChatRobot.exe中，接口具体实现在DWeChatRobot.dll中。

大佬大佬，就是您demo里也有引用吖。。而且怎么现在调用都需要提供pid呢
![image](https://user-images.githubusercontent.com/49738599/185037740-16963891-0b89-47c1-ac37-673e9e317e56.png)

**Comment by ljc545w** [comment]
这段代码是后来其他人贡献的，在引用那里右键添加COM对象就行了。
需要提供pid是为了兼容多开。C#我不熟悉，所以没怎么更新过。

**Comment by ljc545w** [comment]
这段代码是后来其他人贡献的，在引用那里右键添加COM对象就行了。
需要提供pid是为了兼容多开。C#我不熟悉，所以没怎么更新过。

**Comment by XiuiManeia** [comment]
> 这段代码是后来其他人贡献的，在引用那里右键添加COM对象就行了。 需要提供pid是为了兼容多开。C#我不熟悉，所以没怎么更新过。

嘿嘿谢谢大佬，我终于完成了！！！万分感谢！！！！！！！！

**Comment by XiuiManeia** [comment]
> 这段代码是后来其他人贡献的，在引用那里右键添加COM对象就行了。 需要提供pid是为了兼容多开。C#我不熟悉，所以没怎么更新过。

额。。大佬，昨天都完美运行就没弄了。。今天继续写的时候一运行微信就崩溃，重启也不行，unregserver也不行，重新编译引用也不行，有啥办法嘛。。。
![image](https://user-images.githubusercontent.com/49738599/185381481-a71b7b5d-0d20-481f-a9b3-7071732ea70c.png)

**Comment by ljc545w** [comment]
版本怎么是3.7.0.26，如果拉的master分支，对应的微信版本应该是3.7.0.30
