### ISSUE TITLE
接收消息时表情（动图）消息会发送两次

### ISSUE THREAD

**Issue by amchii** [ljc545w/ComWeChatRobot#82]
开启消息接收之后，我发现表情消息如果是动图或比较大的图会发送两次，即只发了一个表情却回调了两次且消息内容一模一样。谁可以测一下是不是也这样？

**Comment by ljc545w** [comment]
消息确实有可能重复，可能是心跳时同步的。可以根据消息id进行过滤。

**Comment by amchii** [comment]
不知道是什么策略，你也可以试试，我这边是只有大尺寸表情图（高清、动图）会重复两次。我来做一个workaround吧，在com服务端对消息做一个几秒内去重。
