### ISSUE TITLE
现在接受消息的方式有几种？  有哪里可以参考的嘛？

### ISSUE THREAD

**Issue by feather8013** [ljc545w/ComWeChatRobot#83]
想用js来写客户端，接口的调用已经调通。 接收消息的方式一直没看懂。   作者能否建个群，好讨论，不然只能自己琢磨。

**Comment by ljc545w** [comment]
目前有两种方式，一种是socket，一种是com连接点。可以参考python中的实现。
后面会考虑建交流群的。

**Comment by feather8013** [comment]
数据交换格式使用json 是否会更加方便， 现在是字节流。

**Comment by ljc545w** [comment]
> 找到了socket消息接收方式，数据交换格式使用json 是否会更加方便， 现在是字节流。

最近就会优化，之前想尽可能少的引入第三方库，所以设计了结构体。

**Comment by ljc545w** [comment]
消息格式已经修改为json了。
