### ISSUE TITLE
确认一下， 现在接受文本消息是无法获取at的用户wxid吗？

### ISSUE THREAD

**Issue by feather8013** [ljc545w/ComWeChatRobot#87]

**Comment by ljc545w** [comment]
没有被艾特人的wxid

**Comment by feather8013** [comment]
> 没有被艾特人的wxid

大佬，这一块有没有可能加一下。群聊管理的时候， 艾特信息比较重要。

**Comment by ljc545w** [comment]
请耐心等几天，后面把接收消息的格式改成json，也会补充这些信息的。

**Comment by ljc545w** [comment]
补充了一个extrainfo字段，base64解码后以protobuf格式解析，就能拿到被艾特人wxid了。

**Comment by duo** [comment]
> 补充了一个extrainfo字段，base64解码后以protobuf格式解析，就能拿到被艾特人wxid了。

请问 extrainfo 的 protobuf 定义有么?
