### ISSUE TITLE
C#用的那个一个版本的微信呢

### ISSUE THREAD

**Issue by xxtkong** [ljc545w/ComWeChatRobot#89]
更新dll文件后，就不行了。请问大佬用的哪一个版本的微信呢？

**Comment by pauljohn21** [comment]
我现在依然在用3.6.0.18.等大佬更新c#实例中

**Comment by ljc545w** [comment]
建议你们用http自己封装吧，Release/socket文件夹下，调用wxDriver注入和启动监听。  
C# 我也不是很懂，封装需要的时间太久了。
