### ISSUE TITLE
dll要怎么用，好像只有com的调用代码

### ISSUE THREAD

**Issue by kanadeblisst** [ljc545w/ComWeChatRobot#9]
dll注入之后打印了几个地址，应该怎么在Python中使用

**Comment by ljc545w** [comment]
所有的API写在Python/wxRobot.py里面，Python/test.py提供了几个例子，当然wxRobot.py也只是一个示例，可以根据实际需要进行更好的封装。注入之后会打印地址，你可能使用了Debug版本的，建议使用Release版本

**Comment by kanadeblisst** [comment]
看懂了大概，功能在dll里写的，然后exe用CreateRemoteThread调用在注册成com

**Comment by ljc545w** [comment]
> 看懂了大概，功能在dll里写的，然后exe用CreateRemoteThread调用在注册成com

对的，实现思路就是这样。下一次提交新功能再放博客地址吧
