### ISSUE TITLE
请问下，最新版的那个console窗口是必须的吗？能在编译选项上去掉吗？

### ISSUE THREAD

**Issue by cyonjan** [ljc545w/ComWeChatRobot#90]
最新socket版的那个console窗口是必须的吗？可以在编译选项上去掉吗？

**Comment by ljc545w** [comment]
不开启log就不会有黑窗。

**Comment by ljc545w** [comment]
调用WECHAT_LOG_START_HOOK才会生成一个console窗口。

**Comment by cyonjan** [comment]
测试了，果真如此，谢谢！你的程序写的很漂亮，读着就舒服。
