### ISSUE TITLE
终于等来了 http 

### ISSUE THREAD

**Issue by oooooos** [ljc545w/ComWeChatRobot#92]
请问一下 注入哪个dll啊 默认端口多少

**Comment by 0honus0** [comment]
要不用python提供的例子，要不自己调用wxDrive.dll的start_listen函数

**Comment by oooooos** [comment]
> 要不用python提供的例子，要不自己调用wxDrive.dll的start_listen函数

调用start_listen一直返回false 已经执行了CWeChatRobot.exe /regserver 还需要做其他操作吗

**Comment by 0honus0** [comment]
> > 要不用python提供的例子，要不自己调用wxDrive.dll的start_listen函数
> 
> 调用start_listen一直返回false 已经执行了CWeChatRobot.exe /regserver 还需要做其他操作吗

啊，我没试过这样启动，我自己调用dll的start_listen启动的，是可以用的

**Comment by ljc545w** [comment]
http用不到CWeChatRobot.exe，就用wxDriver.dll和SWeChatRobot.dll就行了。
至于怎么调用API，还请仔细阅读wxDriver.py中的代码。
我个人认为写的并不难懂，希望能帮到你。

**Comment by oooooos** [comment]
> http用不到CWeChatRobot.exe，就用wxDriver.dll和SWeChatRobot.dll就行了。 至于怎么调用API，还请仔细阅读wxDriver.py中的代码。 我个人认为写的并不难懂，希望能帮到你。

谢谢大佬 我搞错了 以为时wxDriver.dll配合CWeChatRobot.exe使用 现在已经搞定

**Comment by oooooos** [comment]
@ljc545w 
大佬帮忙看一下呢
post方式会报错 {"err_msg":"[json.exception.type_error.302] type must be string, but is null","result":"ERROR"}
get方式微信会直接崩溃退出 如下图
![image](https://user-images.githubusercontent.com/56820459/186553362-98d002b4-af5d-4cb7-a3e8-1e12d7504125.png)


请求地址：http://127.0.0.1:9999/api/?type=2
JSON参数：{
    "data":{"msg":"333322221111","wxid":"filehelper"}
}

**Comment by oooooos** [comment]
@ljc545w  我把JSON改成{"msg":"333322221111","wxid":"filehelper"}后 POST也直接崩溃了

**Comment by ljc545w** [comment]
参数写错了，没必要在外面包一层data，写成`{"msg":"333322221111","wxid":"filehelper"}`就行。python里面留了一个类，可以根据api编号拿到参数模板，报错的话可以对比一下。

**Comment by ljc545w** [comment]
post参数传递之前还需要序列化，在python里面，就是json.dumps(body)

**Comment by oooooos** [comment]
我是直接用POSTMAN测试的接口 是不是微信版本不对 我用的master生成好的dll 对应的微信版本是多少呀

**Comment by ljc545w** [comment]
版本是3.7.0.30，README里都有写的。

**Comment by oooooos** [comment]
发送已经搞定了 谢谢大佬

**Comment by oooooos** [comment]
接收消息部分 socket 服务创建了 测试正常 也开启接收消息hook成功 但没有消息进来 会是什么原因导致的呀 Python代码看的不是太懂 还请大佬指点一下啊

**Comment by ljc545w** [comment]
信息太少，无法判断原因，很抱歉不能帮到你

**Comment by oooooos** [comment]
调用步骤 开启一个socket服务 端口8000 然后调用type9接口参数传{"port": 8000} 还需要做其他操作吗 本地的socket服务地址是ws://127.0.0.1:8000 需要做地址配备吗

**Comment by ljc545w** [comment]
尝试使用socket而非websocket作为server。其他步骤没有问题。

**Comment by oooooos** [comment]
果然问题是在这里 谢谢大佬。
接收到的消息是乱码 怎么处理啊  是不是我这边需要调整字符集编码
![image](https://user-images.githubusercontent.com/56820459/186847563-9ab05e7b-3fe8-4aaf-98cb-6f041503f06b.png)

**Comment by oooooos** [comment]
更换了最新的dll 已经解决了

**Comment by ljc545w** [comment]
之前的格式是一个C结构体。解决了就好

**Comment by oooooos** [comment]
py示例内的所有接口都测了一下  设置群公告会导致微信崩溃  图片HOOK 和语音HOOK开启接口返回正常 但没有接收效果 图片和语音没有保存下来 就这三个问题 其他所有接口均正常 大佬牛🍺 手动点赞

**Comment by ljc545w** [comment]
有空我看看那三个接口。之前测试都是正常的，如果方便还请提供下测试用例。感谢

**Comment by oooooos** [comment]
@ljc545w 不好意思哈 大佬 这几天有点忙 需要我这边提供什么东西呢 我配合您处理

**Comment by yyzz1987431** [comment]
@ljc545w 
微信版本3.7.30
python http接口，设置图片、语音hook
    #开启语音hook
    VOICE_HOOK=post_wechat_http_api(APIS.WECHAT_MSG_START_VOICE_HOOK, 8000, {"save_path":"D:/ruoyi/"})
    print('语音hook',VOICE_HOOK)
    #开启图片hook
    IMAGE_HOOK = post_wechat_http_api(APIS.WECHAT_MSG_START_IMAGE_HOOK, 8000, {"save_path": "D:/ruoyi/"})
    print('图片hook',IMAGE_HOOK)
  发送vx 消息 一张图片、一段语音
期望结果：D:/ruoyi/文件夹能收到语音和图片

故障现象：1.实时消息接口共收到三条消息，两条图片消息、一条语音消息，应该是两条？
                  2. D:/ruoyi/ 未出现语音和图片文件
[日志.txt](https://github.com/ljc545w/ComWeChatRobot/files/9503100/default.txt)

**Comment by oooooos** [comment]
![image](https://user-images.githubusercontent.com/56820459/188814007-dc735f92-9eed-4790-a8d4-45f00b60c849.png)

**Comment by ljc545w** [comment]
> 

这是个bug，下次提交修复。

**Comment by ljc545w** [comment]
> 

设置群公告，这个需要等我看看问题原因。

**Comment by ljc545w** [comment]
@oooooos 暂时无法复现设置群公告的崩溃问题，测试都是正常的。
