### ISSUE TITLE
实时消息接收接口出现乱码消息

### ISSUE THREAD

**Issue by yyzz1987431** [ljc545w/ComWeChatRobot#93]
{'pid': 261, 'time': '', 'filepath': '', 'type': 0, 'isSendMsg': 0, 'msgid': 0, 'wxid': '', 'message': '', 'from': 'בּ墲狿\x0f龐鼪Ǥ'}
{'pid': 261, 'time': '', 'filepath': '', 'type': 1866755407, 'isSendMsg': 1198943577, 'msgid': 5799036764346135623, 'wxid': '††††㰠楤敧瑳㰾嬡䑃呁孁룤\ue480趽맥\ue6b3ꖗ룤\ue58d鲖ꓥ\ue89a肨髧\ue584Ꞥ鏥\uefa5貼껨\ue4b2蚺룤\ue6aa邁胦\ue696薕뫤\uef8b貼郥\ue593낈뫤\ue586袾ꓥ\ue49a몺胣岂屮\ue46eꂽ매\ue79fꖟ臩\uef93貼菨\ue8bd馿매\ue888뒯볯\ue58c뚅菨\ue58c躐냥\ue5b1薿鳦\ue689', 'message': '놷蓦\ue38f芀湜湜触\ue480ꖻ볯\ue68c醈胥\ue892覧뻥\ue897馿鯦\ue5b4较迦\ue590趉鏩\ue5baꮞ볯\ue48c몸軦\ue4a5许軥\ue7bb蒚鿦\ue7b4ꮁ룤\ue68e뒰뫦\ue690뺉藥\ue5a5몜髧\ue784蚐껨\ue5ba몟ꇧ\ue380芀湜湜룤\ue78d뚄볯\ue78c몼臧\ue7ab몼냦\uefb4貼蛥\ue5acꦤꓥ\ue9aa뺚蛧\ue3ac芀湜湜軧\ue5b0ꢜ韩\ue9ae颢鷦\ue4a5蚺볯\ue48cꂽ蟨\ue5aa놷臥\ue59a붥鷩\ue5a2릯뿨\ue499ꪸ蛥\ue5acꦤ髧\ue584蚇ꓥ\ue487蚺郥\uef97龼湜湜룤\ue58dꢦ闧\ue899肨賥\uefba貼룤\ue880략臨\ue88a誁뿥\ue583鞾嵝㰾搯杩獥㹴湜††††††††⼼潴湰睥尾\u206e†††††††尠\u206e†††††††㰠瑩浥尾\u206e†††††††††㰠瑩浥桳睯祴数㠾⼼瑩浥桳睯祴数尾\u206e†††††††††㰠楴汴㹥ℼ䍛䅄䅔\ue45b肸뷤\ue58d뎹韦\ue4a5趸雥\ue59c骤꣨\ue780蒚ꓥ\ue5a7ꖓ볯\ue88c늮뫤\ue486ꪸ臦\ue690隀闦\ue485论볯\ue58c鎐裥\ue4b0蚺뻥\ue588骤뫤\ue3ba芀湜湜뷤\ue4a0龹鿧\ue9a5鎁볯\ue88c붃뿨\ue499袹꿨\uefb4貼藥\ue8b6貃郥\ue58e놰뿥\ue685覜럦\ue6b1辄胣岂屮\ue66e肉믤\uefa5貼裦\ue591銀\ua7e8\ue589鞾뿨\ue699뒛菥\ue68f邏觥\ue98d몓黥\uefab貼룤\ue6baꖎ룤\ue58b뮎髧\ue684뒟臧\ue4ab躸냦\ue6b4邺触\ue5beꖅ鳥\ue7ba蒚退\ue886몮鿥ቿ洀犸\x0e\u1ff0鼬Ǥ', 'sendto': 'בּ墲狿\x0e龐鼪Ǥ'}

**Comment by ljc545w** [comment]
是偶尔出现，还是一直这样？
