### ISSUE TITLE
发现貌似没有艾特人的功能，https://github.com/newNcy/wxbot 这是我根据这个项目自己实现的版本，目前卡在艾特上，不知道能否提供思路

### ISSUE THREAD

**Issue by newNcy** [ljc545w/ComWeChatRobot#96]

**Comment by ljc545w** [comment]
SendAtText就是发送群艾特的

**Comment by newNcy** [comment]
有讨论群吗，想学习下

**Comment by ljc545w** [comment]
我没有创群聊。有使用者创了个群，issue里应该可以找到

**Comment by newNcy** [comment]
有转发图片的思路吗大佬，发现发送文本和图片的地方和上层调用都断不到

**Comment by newNcy** [comment]
给个联系方式交流下吗

**Comment by ljc545w** [comment]
转发消息的地方我找过，逻辑比较复杂，所以没有动手实现。你可以从消息ID切入。

**Comment by duo** [comment]
> 转发消息的地方我找过，逻辑比较复杂，所以没有动手实现。你可以从消息ID切入。

这个我之前倒是整了，需要用到消息的 local id

```
	DWORD dllBaseAddress = GetWeChatWinBase();
	DWORD callAddress1 = dllBaseAddress + 0x771980;
	DWORD callAddress2 = dllBaseAddress + 0x521760;

	__asm {
		pushad;
		mov eax, 0x5000100;
		push eax;
		mov ecx, localId;
		push ecx;
		lea edi, wxId;
		sub esp, 0x14;
		mov ecx, esp;
		push edi;
		call callAddress1;
		call callAddress2;
		add esp, 0x1C;
		popad;
	}
```

**Comment by newNcy** [comment]
> > 转发消息的地方我找过，逻辑比较复杂，所以没有动手实现。你可以从消息ID切入。
> 
> 这个我之前倒是整了，需要用到消息的 local id
> 
> ```
> 	DWORD dllBaseAddress = GetWeChatWinBase();
> 	DWORD callAddress1 = dllBaseAddress + 0x771980;
> 	DWORD callAddress2 = dllBaseAddress + 0x521760;
> 
> 	__asm {
> 		pushad;
> 		mov eax, 0x5000100;
> 		push eax;
> 		mov ecx, localId;
> 		push ecx;
> 		lea edi, wxId;
> 		sub esp, 0x14;
> 		mov ecx, esp;
> 		push edi;
> 		call callAddress1;
> 		call callAddress2;
> 		add esp, 0x1C;
> 		popad;
> 	}
> ```

非常感谢，请问这个什么版本，我是3.7.5.23 估计不能直接用，能否给个思路

**Comment by duo** [comment]
> > > 转发消息的地方我找过，逻辑比较复杂，所以没有动手实现。你可以从消息ID切入。
> > 
> > 
> > 这个我之前倒是整了，需要用到消息的 local id
> > ```
> > 	DWORD dllBaseAddress = GetWeChatWinBase();
> > 	DWORD callAddress1 = dllBaseAddress + 0x771980;
> > 	DWORD callAddress2 = dllBaseAddress + 0x521760;
> > 
> > 	__asm {
> > 		pushad;
> > 		mov eax, 0x5000100;
> > 		push eax;
> > 		mov ecx, localId;
> > 		push ecx;
> > 		lea edi, wxId;
> > 		sub esp, 0x14;
> > 		mov ecx, esp;
> > 		push edi;
> > 		call callAddress1;
> > 		call callAddress2;
> > 		add esp, 0x1C;
> > 		popad;
> > 	}
> > ```
> 
> 非常感谢，请问这个什么版本，我是3.7.5.23 估计不能直接用，能否给个思路

是 master 的 3.7.0.30 这个版本
思路的话，时间有点久了，当时好像是 IDA 搜 forward 关键字然后各种断点看了...

**Comment by ljc545w** [comment]
我已经根据@duo 提供的偏移将转发消息加入到master分支中，具体可查看#110。
