### ISSUE TITLE
怎样在64位的win10系统中注册com呀？

### ISSUE THREAD

**Issue by lycanthropes** [ljc545w/ComWeChatRobot#97]
我使用的是64位系统，在以管理员模式打开cmd后，运行CWeChatRobot.exe /regserver命令后没有直接反应，既没报错也没提示说成功，只是立即下移到新的一行，不知道这是不是算注册成功了呀？
![image](https://user-images.githubusercontent.com/38000321/187108323-53a0231a-8258-4b83-bd20-66b71645e984.png)

**Comment by lycanthropes** [comment]
对了，我的微信版本是3.7.6.29

**Comment by ljc545w** [comment]
没有提示就没问题的。另外不支持3.7.6.29版本。请使用3.7.0.30。
