### ISSUE TITLE
python demo 接收到message乱码,还有报错

### ISSUE THREAD

**Issue by September999999999** [ljc545w/ComWeChatRobot#98]
![image](https://user-images.githubusercontent.com/32701871/187134465-7bdbe353-f8ab-47ff-92be-1b7390ddcf58.png)
`{'extrainfo': b'\x1a$\x08\x02\x12 01b79d73c1441667aa4443a5eab8e3c5', 'filepath': '', 'isSendMsg': 1, 'message': '娴嬭瘯', 'msgid': 1115852271143770924, 'pid': 6916, 'sender': '18794550263@chatroom', 'time': '2022-08-29 14:12:34', 'type': 1, 'wxid': '18794550263@chatroom'}`

**Comment by ljc545w** [comment]
这个地方编码转换有点问题，COM把utf8数据当作gbk解析了。下次提交修复。

**Comment by September999999999** [comment]
> 这个地方编码转换有点问题，COM把utf8数据当作gbk解析了。下次提交修复。

好的,感谢大佬
